### ISSUE TITLE
Getting many issues while running openvidu in Cordova

### ISSUE THREAD

**Issue by abhilashfancy** [OpenVidu/openvidu#110]
I have used the openvidu-js-node tutorial and used the v2.3 app.js and openvidu-browser-2.3.0.js in my cordova app. I am able to login by using the predefined credentials of different users. Then when I give a session name and hit join I am navigated to the video screen where I am able to see my own video clearly but in place where the remote video should occur just shows the remote participant name and is just empty. And at the remote side it shows no sign of the second member. Let me make it very clear. If there are three people out of which two are accessing the page in their browsers and other one is accessing the page from cordova app the two users using browsers can clearly communicate with each other. But when the third member connects from cordova he is able to see the names of the two participants using browser but cannot see their video and the two users using browser can't even see the name of the user using cordova. Please help me...

**Comment by micaelgallego** [comment]
How are you deployed OpenVidu server and KMS?

If you have your phone in the same network than your server (for example
connecting boths to the same wifi) then it should work. But if you try to
connect your mobile app using operator 4G connection, or the mobile is in
other network than servers, then you need to install COTURN server.

**Comment by abhilashfancy** [comment]
I have deployed Openvidu and KMS server on Digital Ocean using their respective docker images. I have tested with two devices on same network also. But they work only when they are using browsers. They do not work when using cordova. Same goes for 4G connection. I have even installed, properly configured and tested COTURN server which is also hosted on Digital Ocean.

**Comment by micaelgallego** [comment]
Only for clarification, openvidu web application is working, but cordova
application is not working in the same devices?

We don't have any updated example using Cordova, but with an old example we
get a working ionic application with crosswalk. Maybe the chrome integrated
in croaswalk is very old and it is not compatible with openvidu-browser.js.
Do you have any error? Can you compare openvidu server log for sucess
connection (from.browser) with unsuccessful connectiom (from.cordova)?

**Comment by abhilashfancy** [comment]
Here is my log for success connection to the session named "session"
```
2018-08-16 15:21:23,560 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:23,559 [-4443-exec-3] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {iyqxgylio8q62igd={}}
 
 2018-08-16 15:21:23,577 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:23,576 [-4443-exec-6] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {iyqxgylio8q62igd={wss://greenoxeco.in:4443?sessionId=iyqxgylio8q62igd&token=datpkgsuncuhg7xx&role=PUBLISHER=PUBLISHER}}
 
 2018-08-16 15:21:24,652 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:24,651 [-4443-exec-2] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: qqtvghlp4me8bu9gmbp5r7e8tu
 
 2018-08-16 15:21:24,656 DEBG 'openvidu-server' stdout output:
 [WARN] 2018-08-16 15:21:24,656 [7e8tu-e22-t0] io.openvidu.server.kurento.core.KurentoSessionManager (createSession) - No session 'iyqxgylio8q62igd' exists yet. Created one using KurentoClient 'manager_ServerManager'.
 
 2018-08-16 15:21:24,657 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:24,656 [7e8tu-e22-t0] io.openvidu.server.core.Session (createPipeline) - SESSION iyqxgylio8q62igd: Creating MediaPipeline
 
 2018-08-16 15:21:24,659 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:24,658 [7e8tu-e22-t0] io.openvidu.server.core.Session (join) - SESSION iyqxgylio8q62igd: Added participant [participantPrivateId=qqtvghlp4me8bu9gmbp5r7e8tu, participantPublicId=3iuhsooxaue0d2yr, streaming=false]
 
 2018-08-16 15:21:25,769 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:25,767 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'publish' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:25,858 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:25,858 [7e8tu-e22-t0] io.openvidu.server.kurento.core.KurentoParticipant (publishToRoom) - PARTICIPANT 3iuhsooxaue0d2yr: Request to publish video in room iyqxgylio8q62igd (sdp type OFFER)
 
 2018-08-16 15:21:25,868 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:25,868 [7e8tu-e22-t0] io.openvidu.server.kurento.core.KurentoParticipant (publishToRoom) - PARTICIPANT 3iuhsooxaue0d2yr: Is now publishing video in room iyqxgylio8q62igd
 
 2018-08-16 15:21:25,889 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:25,889 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:25,898 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:25,889 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 [INFO] 2018-08-16 15:21:25,889 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:25,898 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:25,889 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 [INFO] 2018-08-16 15:21:25,890 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 [INFO] 2018-08-16 15:21:25,890 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 [INFO] 2018-08-16 15:21:25,890 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 [INFO] 2018-08-16 15:21:25,890 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:26,296 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:26,296 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:26,300 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:26,300 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:26,322 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:26,321 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:26,346 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:26,345 [7e8tu-e22-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 3iuhsooxaue0d2yr is calling method 'onIceCandidate' in session iyqxgylio8q62igd
 
 2018-08-16 15:21:26,971 DEBG 'openvidu-server' stdout output:
 [WARN] 2018-08-16 15:21:26,970 [Exec-e3-t176] io.openvidu.server.kurento.core.KurentoParticipant (lambda$addEndpointListeners$5) - ICE CANDIDATE SELECTED (3iuhsooxaue0d2yr_CAMERA_CPNLW): LOCAL CANDIDATE: candidate:16 1 UDP 2013266431 139.59.40.52 42998 typ host | REMOTE CANDIDATE: candidate:2781507712 1 UDP 1685987071 45.113.66.34 48226 typ srflx raddr 192.168.1.5 rport 48226 | TIMESTAMP: 1534432886970
 
 2018-08-16 15:21:26,971 DEBG 'openvidu-server' stdout output:
 [WARN] 2018-08-16 15:21:26,971 [Exec-e3-t185] io.openvidu.server.kurento.core.KurentoParticipant (lambda$addEndpointListeners$5) - ICE CANDIDATE SELECTED (3iuhsooxaue0d2yr_CAMERA_CPNLW): LOCAL CANDIDATE: candidate:16 1 UDP 2013266431 139.59.40.52 42998 typ host | REMOTE CANDIDATE: candidate:2781507712 1 UDP 1685987071 45.113.66.34 48226 typ srflx raddr 192.168.1.5 rport 48226 | TIMESTAMP: 1534432886971
 
 2018-08-16 15:21:29,243 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:29,242 [Exec-e3-t185] io.openvidu.server.kurento.core.KurentoParticipant (lambda$addEndpointListeners$2) - Media flow out state change (3iuhsooxaue0d2yr_CAMERA_CPNLW) -> STATE: FLOWING | SOURCE: 67db210e-1fcd-42ec-ad77-c9f5964e7a75_kurento.MediaPipeline/68882d12-8247-43c6-b880-9b1ec2adbe44_kurento.WebRtcEndpoint | PAD: default | MEDIATYPE: AUDIO | TIMESTAMP: 1534432889242
 
 2018-08-16 15:21:29,288 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:21:29,287 [Exec-e3-t185] io.openvidu.server.kurento.core.KurentoParticipant (lambda$addEndpointListeners$2) - Media flow out state change (3iuhsooxaue0d2yr_CAMERA_CPNLW) -> STATE: FLOWING | SOURCE: 67db210e-1fcd-42ec-ad77-c9f5964e7a75_kurento.MediaPipeline/68882d12-8247-43c6-b880-9b1ec2adbe44_kurento.WebRtcEndpoint | PAD: default | MEDIATYPE: VIDEO | TIMESTAMP: 1534432889287
```
and here is the log for the connection from cordova app to the same server and the same session "session"
```
2018-08-16 15:27:30,959 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:27:30,958 [4443-exec-10] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {iyqxgylio8q62igd={wss://greenoxeco.in:4443?sessionId=iyqxgylio8q62igd&token=7h304fybru49u790&role=PUBLISHER=PUBLISHER}}
 
 2018-08-16 15:27:31,123 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:27:31,122 [kScheduler-1] io.openvidu.server.rpc.RpcHandler (afterConnectionClosed) - After connection closed for WebSocket session: kiipom9ubedic2ps99n7siclla - Status: null
 
 2018-08-16 15:27:31,466 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:27:31,466 [-4443-exec-1] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: u0kdpmr2h97hl2tdkrb0o2clki
 
 2018-08-16 15:27:31,467 DEBG 'openvidu-server' stdout output:
 [INFO] 2018-08-16 15:27:31,467 [2clki-e24-t0] io.openvidu.server.core.Session (join) - SESSION iyqxgylio8q62igd: Added participant [participantPrivateId=u0kdpmr2h97hl2tdkrb0o2clki, participantPublicId=zse0scduy1kj5bxk, streaming=false]

```
![img_20180816_205931](https://user-images.githubusercontent.com/13430073/44222785-4ab64300-a1a3-11e8-8255-8d16c1255842.jpg)
and here are the logs from the console of cordova
```
Request of TOKEN gone WELL (TOKEN:wss://greenoxeco.in:4443?sessionId=iyqxgylio8q62igd&token=ui6klhse2vcmpixl&role=PUBLISHER)
openvidu-browser-2.3.0.js:3327 'OpenVidu' initialized
app.js:45 session: Session  token:  wss://greenoxeco.in:4443?sessionId=iyqxgylio8q62igd&token=ui6klhse2vcmpixl&role=PUBLISHER
openvidu-browser-2.3.0.js:5989 Connecting websocket to URI: wss://greenoxeco.in:4443/openvidu
openvidu-browser-2.3.0.js:6153 WebSocket connected to wss://greenoxeco.in:4443/openvidu
openvidu-browser-2.3.0.js:5969 --------- ONCONNECTED -----------
openvidu-browser-2.3.0.js:6072 Starting ping (if configured)
openvidu-browser-2.3.0.js:3681 Sending request: {method:"joinRoom", params: {"token":"wss://greenoxeco.in:4443?sessionId=iyqxgylio8q62igd&token=ui6klhse2vcmpixl&role=PUBLISHER","session":"iyqxgylio8q62igd","metadata":"{\"clientData\":\"Ved\"}","secret":"","recorder":false}}
openvidu-browser-2.3.0.js:6012 Request: method:joinRoom params:{"token":"wss://greenoxeco.in:4443?sessionId=iyqxgylio8q62igd&token=ui6klhse2vcmpixl&role=PUBLISHER","session":"iyqxgylio8q62igd","metadata":"{\"clientData\":\"Ved\"}","secret":"","recorder":false}
openvidu-browser-2.3.0.js:6030 Response: {"id":"erjvo335kbdxmmsx","metadata":"{\"clientData\":\"Ved\"}%/%{\"serverData\":\"ved_publisher\"}","value":[{"id":"3iuhsooxaue0d2yr","metadata":"{\"clientData\":\"Abhilash\"}%/%{\"serverData\":\"abhilash_publisher\"}","streams":[{"id":"3iuhsooxaue0d2yr_CAMERA_CPNLW","hasAudio":true,"hasVideo":true,"videoActive":true,"audioActive":true,"typeOfVideo":"CAMERA","frameRate":30,"videoDimensions":"{\"width\":640,\"height\":480}"}]}],"sessionId":"vb3cnp30aa56tb5u05im1e6uni"}
openvidu-browser-2.3.0.js:2991 'Connection' created (local)
openvidu-browser-2.3.0.js:2991 'Connection' created (remote) with 'connectionId' [3iuhsooxaue0d2yr]
openvidu-browser-2.3.0.js:3035 Remote 'Connection' with 'connectionId' [3iuhsooxaue0d2yr] is now configured for receiving Streams with options:  Object
openvidu-browser-2.3.0.js:4414 Event 'streamCreated' triggered by 'Session' StreamEvent
openvidu-browser-2.3.0.js:4226 Subscribing to 3iuhsooxaue0d2yr
openvidu-browser-2.3.0.js:5113 'Session.subscribe(Stream)' called. Constraints of generate SDP offer Object
openvidu-browser-2.3.0.js:5245 Event 'videoElementCreated' triggered by 'Subscriber' VideoElementEvent
openvidu-browser-2.3.0.js:4882 Video srcObject [[object MediaStream]] updated in stream [undefined]
openvidu-browser-2.3.0.js:5245 Event 'videoElementCreated' triggered by 'Publisher' VideoElementEvent
openvidu-browser-2.3.0.js:5226 Your local 'Stream' with id [undefined] video is now playing
```

**Comment by ajay01994** [comment]
Same issue here, anyone who can address it or has got some results on it?

**Comment by maddluxx** [comment]
Hello!
I have similar issue, but without Cordova.

I'm using AWS instance configured with your AWS Cloud Formation template and tutorial.
I have both (they were started about Jun 15):
1. Demo one like this - https://openvidu.io/docs/deployment/deploying-demos-aws/
2. And custom - https://openvidu.io/docs/deployment/deploying-aws/

Tutorial apps ran good on both servers until recent time (not sure what particular date though, but at the beginning of August it was fine for sure). My customized apps were working too. It was great.

Now I'm experiencing the issue just like @abhilashfancy  described above in his first post - I can log in to my apps and enter sessions but I cannot see remote feeds. Each user can see just their own feed and nothing else. But video-containers and nicknames are displayed well. All logs seem clean and healthy though...
Openvidu default dashboard connection test doesn't work either, just hangs there forever, btw. 

First I thought that it may be caused by SSL-certificates which I renewed recently, but I renewed them just fine, all that was needed is to run letsencrypt auto-update script and restart the services. 
Also I started newest instance from your AWS template (it's the third instance with OpenVidu in my collection), so I could test if issues are there for newest openvidu-browser and server versions - and I've found those issues there too!

I experience this with both Chrome and Firefox, on 2 of my PCs and Android mobile Chrome. I mostly tested openvidu-js-node and openvidu-js-java and my apps which are based on openvidu-js-node.
Tested it on your instance https://demos.openvidu.io/basic-webinar/ and don't have an issue. So there should be some simple answer..

So please, let me know, if you know why is it happening and if there is solution or if you are working on the solution but it's just not released here yet? Or maybe you have some insight what I did wrong (but it's clearly just pure following to your tutorials!)

**Comment by pabloFuente** [comment]
I'll check this today. If there's any problem with AWS instances we will try to solve asap.

**Comment by pabloFuente** [comment]
So, we have just tested AWS deployment with latest release and it is working fine for all 3 proposed scenarios dependening on the certificate strategy chosen (insecure self-signed certificate, automatic Let's Encrypt certificate and custom certificate).

Can you provide us with any further information?

**Comment by maddluxx** [comment]
Sure, I can provide any information that may help. From both instances: the one that I used to work with, and the clean new installation from AWS template (https://openvidu.io/docs/deployment/deploying-aws/) with tutorial apps installed there.
Could you please specify what would you like to review?
Some specific logs or packages versions?

The only difference I noticed for now is nodejs version. There is node v8.12.0 on new instance and v8.11.3 on my first and main development one - but as I said the issue appears on both even with default tutorials apps. 
Also, first I deployed t2.large instance, but then I tested with t2.xlarge as well - no difference.
Also, after multiple tests I've found that sometimes (but pretty rare - about 1/50 times) I can see and hear remote feed - one time it happened right after exiting and entering the session again, and another time - when my session was just opened for a long time and suddenly in one of the browser windows both feeds appeared..

**Comment by pabloFuente** [comment]
Please clarify two points for me:

1) If you connect to `https://YOUR_AMAZON_MACHINE_IP:4443/` in the newest launched machine and perform the test provided in OpenVidu Server dashboard, does it end correctly? (receiving remote video)
2) If you deploy the Demos as stated here: https://openvidu.io/docs/deployment/deploying-demos-aws/, do they work OK as they come? 

What I really cannot understand is the fact that you deployed a brand new AWS Cloud Formation stack of OpenVidu Server and it didn't work. Our Continuous Integration system states those templates are working fine right now.

**Comment by micaelgallego** [comment]
Maybe the network in which you are performing tests is an special one with
very restrictive NAT...

**Comment by maddluxx** [comment]
1. Sometimes it's successful.
Sometimes it's half-successful - video shows just for a second and then it's blank but with green check mark (like this http://prntscr.com/kw1ras).
Sometimes it's half-successful the other way around - video shows fine, but there is no any text feedback.
Sometimes it just hangs there forever like this http://prntscr.com/kw1rq0 and sometimes it hangs even without any feedback in the log. 

The behavior on different instances is as following (There I used letsencrypt option for all examples, as well as same SECRET value, domains are different for different instances though):
1) On my custom instance from June (2018-06-17) - status test page mostly hangs forever and I almost never get webinar app to work. As I said it was fine month ago though, and there were no changes in code or AWS network since then. But apps became broken.
2) On new custom instance created from CF-OpenVidu-latest.json (2018-09-16) with demo apps installed manually - test page half-hangs in about 1/4 of cases, hangs forever in about 1/4 of cases and successful in about 1/2 of cases. Webinar app works pretty much the same: 1/3 cases participants don't see each other, 1/3 cases first participant can see the second but second cannot see the first (or vice versa), and 1/3 cases - both can see each other. Tested with both node and java webinar apps + my custom app based on node webinar.
3) On new demo instance created from CF-OpenVidu-Demos-latest.json (2018-09-25) - surprisingly, status test page works 100% cases. Webinar app and my app work 100% cases too.
4) Demo webinar on OpenVidu site works 100% cases.

This was tested with and without VPN connection, but under the same WiFi.

2. After @micaelgallego mentioned that it can be caused by NAT - I tested all the instances using 4G mobile hotspot instead of my regular WiFi connection. And results are pretty shocking:

1) On my custom instance from June - status test page works 100% cases. Webinar app and my app work 100% cases.
2) On new custom instance created from CF-OpenVidu-latest.json (2018-09-16) with demo apps installed manually - status test page works 100% cases. Webinar app and my app work 100% cases.
3) On new demo instance created from CF-OpenVidu-Demos-latest.json (2018-09-25) - status test page works 100% cases. Webinar app and my app work 100% cases.
4) Demo webinar on OpenVidu site works 100% cases.

Then I asked my colleague to test some of those apps and pages and he got pretty much same failed and successful results with his WiFi (however he has other ISP). Btw, he is located pretty close to me - we are both in Russia currently.
My second colleague located in US has no issues with any of listed apps at all.

3. OK, so it's definitely some network issues, but we still got success for new Demo instance as well as for public demos on OpenVidu site even using WiFi. So I decided to shut the newest Demo instance down and launch one more custom instance with the IP that Demo instance had minutes ago. And this didn't work again - it was actually pretty much the same (even worse) as my first custom instance - worked just sporadically with my WiFi, mostly hanged, but worked well with 4G mobile internet connection.
Therefore, it's not about AWS Elastic IP. Initially I thought that previous IP may be partially blocked by some of Russian ISPs (because of this https://bit.ly/2qSUqTA) - but it's not, AWS IP is totally fine and isn't the cause of my issues.

4. Then I launched fresh Demo instance again and deployed my custom app there. Everything works just fine on this instance both with WiFi and with 4G mobile internet as well.
So there is something wrong in combination of my ISP provider and CF-OpenVidu-latest.json instance configuration that causes the issues.


Conclusion:
1. For now I'll proceed with this new Demo instance. The only thing I don't like about it - is that it didn't configure the custom SECRET I provided when started. So I'll need to configure my custom SECRET manually. If you can specify where is the location of config files that I need to edit for that without breaking anything - it would be awesome.
2. If you have some insight what was causing the issues for all instances created from CF-OpenVidu-latest.json template (at least for some Russian ISPs) - please let me know. Seems like we (and you guys or other users all over the world) can meet issues like this in future again, if we don't know exactly why it happens.


Thank you very much for your responses and I hope my humble research can help you to make your product even more awesome.

**Comment by maddluxx** [comment]
Actually, I've just realized that this way I'm loosing the ability to do recordings, because Demo instance doesn't support that from the box. That's why I migrated to custom one in the first place...

Could you please also shed some light to how can I enable recording support on running Demo instance?

**Comment by maddluxx** [comment]
Hi guys!
If I want to add recording functionality to my working Demo instance, will it be enough if I just add these flags on openvidu-server.jar start as mentioned there 
```
-Dopenvidu.recording=true \
    -Dopenvidu.recording.path=/path/to/video/files \
    -Dopenvidu.recording.public-access=true \
```
or CF-OpenVidu-Demos-latest.json instance is missing something more than that compared to CF-OpenVidu-latest.json?

**Comment by pabloFuente** [comment]
Hi, maddluxx

Here it is explained how to enable recording service:

https://openvidu.io/docs/advanced-features/recording/

Regards

**Comment by micaelgallego** [comment]
I @maddluxx, we are working in the issue right now. It seems related with a bad interaction between KMS and Docker installed in the same server.

For commercial support, please write to openvidu@gmail.com

**Comment by micaelgallego** [comment]
We have good progress solving the issue when Kurento Media Server and Docker are installed in the same machine.

We plan to publish a new release next week (or maybe the next one) with this issue fixed. 

Stay tuned

**Comment by maddluxx** [comment]
Brilliant!
Thank you!

**Comment by maddluxx** [comment]
Hi Micael, Hi Pablo!
I just finished my update to version 2.6 (migrated to a whole new instance CF-OpenVidu-latest) and tested it with my custom apps and with my WiFI connection - works just great, gets connected at the first try!
So my issue is resolved, thank you very much!

**Comment by pabloFuente** [comment]
Glad to hear!

**Comment by anup212** [comment]
Hi I,m facing the same issue remote video not playing, the session is created on both device but video frame is empty. I.m using OpenVidu Pro(latest version) on aws cloud formation

**Comment by adyasasingh5** [comment]
I have used openvidu-ionic and deployed on android mobile,till session and token created it was working fine in android app but after i run 
docker run -p 4443:4443 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/openvidu/recordings:/opt/openvidu/recordings -e openvidu.recording=true -e openvidu.recording.path=/opt/openvidu/recordings openvidu/openvidu-server-kms:2.9.0

i am getting 404 and 406 error for android app.
please solve my issue

**Comment by jinshuai7777** [comment]
Hello. @micaelgallego , @pabloFuente 
I have created OpenVidu Pro stack.
But even though I can see URL in the "Outputs" section, I can't call API using the URL.
(URL:4443).
Couldnot get any reponse.

What was wrong?
