### ISSUE TITLE
How to specify the resolution exactly?

### ISSUE THREAD

**Issue by willylee007** [OpenVidu/openvidu#114]
Hi~
Currently. OpenVidu use [resulution](https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenViduInternal/Interfaces/Public/PublisherProperties.ts#L69) to specify resolution. But this is a [ideal resolution](https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/OpenVidu.ts), so I can't use exact or max/min resolution. 

So a nice interface should look like this, : 
`
    video: {
    width: { ideal: 1280 },
    height: { ideal: 720 }
  }
`
or
`
    video: {
    width: { exact: 1280 },
    height: { exact: 720 }
  }
`
More info refers to [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia).

Best regards.

**Comment by willylee007** [comment]
It seems doesn't work after I set to "exact" according to webrtc-internals's analyze. Is this feature limited by chrome? Or a bug for chrome?

**Comment by pabloFuente** [comment]
Chrome should allow setting any resolution for a video, even with "ideal" parameter. Property `resolution` of OpenVidu Browser `PublisherProperties` interface works fine for customizing the outgoing video resolution. That's because Chrome modifies width and height of the stream internally, even if the camera doesn't support that resolution.

Firefox works in a different way,  relaying on the specific hardware of  the camera. It must support the desired resolution by default, in a hardware level.

**Comment by willylee007** [comment]
It's limited by OpenVidu-server endpoints's bandwith when set a high quality resolution.
Close.
