### ISSUE TITLE
Recorded video only have black frames

### ISSUE THREAD

**Issue by Ali-Dalal** [OpenVidu/openvidu#122]
Hi,

I tried to record a video on AWS (custom config without using the cloudformation), but the recorded video has just a black screen.

does the type of the EC2 play an important role in this case?

jar  command

```
sudo java -jar -Dopenvidu.secret=MY_SECRET -Dopenvidu.recording=true -Dopenvidu.recording.path=/home/ubuntu/videos -Dopenvidu.recording.public-access=true -Dopenvidu.publicurl=https://13.238.159.87:4443/ openvidu-server-2.4.0.jar
```

Thanks

**Comment by pabloFuente** [comment]
*does the type of the EC2 play an important role in this case?* Well, you should use at least a `t2.large` instance. Larger machines are always recommended, of course.

Without further information I cannot really know waht is happening to you. What instructions have you exactly followed for deploying OpenVidu? How did you enabled recording service?

Today I have deployed OpenVidu 2.4.0 in an Ubuntu server in AWS, enabled recording service and recorded some sessions. Results were OK, so must be something related to your specific setup.

**Comment by Ali-Dalal** [comment]
I followed the same instructions on how to deploy it on Ubuntu.

I tried it (Using Ubuntu) on a local laptop (Asus 8 GB ram, core i5) and it worked, but the is a hang every 5 or eight seconds (the video freezes for a very short duration)

Regarding the type of the Ec2, I think it is really important cuz I tried to deploy Ubuntu solution on t2.micro instance and then I got the black screen video.

**Comment by pabloFuente** [comment]
Well, 1 CPU and 1 GB of RAM is definetly not a place where to deploy any kind of Media Server solution, that's for sure.

**Comment by Ali-Dalal** [comment]
When you try to record some samples, does the hang issue occurs also?

> I tried it (Using Ubuntu) on a local laptop (Asus 8 GB ram, core i5) and it worked, but the is a hang every 5 or eight seconds (the video freezes for a very short duration)

**Comment by pabloFuente** [comment]
It is pretty difficult that the quality of the recording is poorer that the quality of the remote streams your clients are receiving in a videocall. OpenVidu remote recording service works as a special participant of the session connecting through a virtual Chrome instance to the session. We then proceed to record the Chrome view and store it under a video file.

Because this Chrome virtual instance is running next to OpenVidu Server, the quality of the relayed streams will generally be maximum at this point (they do not need to travel to other browser somewhere in the planet). So if you recording is getting choppy, then one of these two things must be happening:

1) Your server is not powerful enough. In Amazon try at least a t2.large. But in production environments and depending on the amount of load expected in your server a t2.xlarge would be better.

2) The remote stream is arriving to OpenVidu Server already with some poor quality. Maybe your Publisher network is a complex one, with heavy latency, slow connection or unexpected microcuts. You can check this point by analysing the received stream in a second user. If you see the same behaviour in your recording file and in your Subscriber streams, then the problem could be located in your Publisher.

Regards

**Comment by Ali-Dalal** [comment]
Thanks @pabloFuente 

That clears the idea.
