### ISSUE TITLE
Using MediaStream directly

### ISSUE THREAD

**Issue by vgaudard** [OpenVidu/openvidu#123]
Hello,

I'm writing a small part of a bigger project where I need to handle media streams. I'm using `open-vidu-browser-2.4.0` on the client.

When I need to join a room, I'm given a native `MediaStream`. 

When a remote user joins the same room, I need to pass a native `MediaStream` to another part of the project.

So far, I can handle the input stream with OpenVidu with the following snippet :

```javascript
OpenVidu = new OpenVidu();
...
async function joinSession(stream) {
    let audioTrack = pStream.getAudioTracks()[0];
    let videoTrack = pStream.getVideoTracks()[0];
    let session = this.mOpenVidu.initSession();
    await session.connect(token);
    let publisher = await OpenVidu.initPublisherAsync(undefined, {
        audioSource: audioTrack || false,
        videoSource: videoTrack || false
    });
    session.publish(publisher);
}
```

This works (mostly, there are some unexpected stream events I'm trying to figure out).

However, the only way I've found to get the `MediaStream` published by a remote user is by using [`Stream.mediaStream`](https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/Stream.ts#L122) which is private.

What I would need is to be able to use something like the following snippet at the end of `joinSession`:

```javascript
session.on('streamCreated', (event) => {
    let subscriber = session.subscribe(event.stream);
    someFunction(event.stream.mediaStream); // Or someFunction(subscriber.stream.mediaStream)
});
```

* Is there a reason why `Stream.mediaStream` is private and what is it ?

* Can I use OpenVidu for my use case ?

Thank you

**Comment by pabloFuente** [comment]
Sure. You can access the `mediaStream` object inside Stream class without any problem.

It is private because official OpenVidu Browser API doesn't require developers to access this property at any time. In other words, we cannot support the manipulation of the MediaStream native object and at the same time assure that no problems will appear when doing so. You have to keep in mind that OpenVidu has a client-side SDK but also a server side that might have some problems dealing with unexpected changes in the MediaStream objects of the browsers.

To access the Stream.mediaStream property in vanilla JS, simply access `yourStreamObject.mediaStream`. In TypeScript, you can force a cast of Stream object like this: `(<any>yourStreamObject).mediaStream` or use a method hidden in the docs called `Stream.getMediaStream()` (https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/Stream.ts#L339-L341)

**Comment by vgaudard** [comment]
Assuming nothing in the project modifies the `mediaStream`, are there problems I can expect ?

In my second snippet, I usually get `event.stream.mediaStream === undefined`. Which event should I listen to to ensure `mediaStream` is defined. Is it `streamPlaying` ?

**Comment by pabloFuente** [comment]
_Assuming nothing in the project modifies the mediaStream, are there problems I can expect ?_ 
Shouldn't be any problems, then.

Subscriber's `Stream.mediaStream` objects are given a value at this exact point: https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/Stream.ts#L716

You can try adding your own listener to the internal event you see there (`mediastream-updated`). At that point mediaStream object will be properly defined and MediaStreamTracks properly added to it.

Remember OpenVidu Browser is an opensource project and you can modfy it however you want to fit your particular needs.

**Comment by vgaudard** [comment]
Thanks!
