### ISSUE TITLE
jks issues

### ISSUE THREAD

**Issue by quickstreamingmedia** [OpenVidu/openvidu#13]
i have created jks file using crt and key as per procedure but still ssl is not valid where on other application its fine

**Comment by pabloFuente** [comment]
You are saying that the browser is showing the insecure certificate warning when using the JKS, but it doesn't do so for same CRT and KEY on other app? (On the same URL, of course)

**Comment by quickstreamingmedia** [comment]
i have created jks using key and srt of same domain by running with it still showing insecure

**Comment by quickstreamingmedia** [comment]
ca we enable ws instead of wss on openvidu

**Comment by pabloFuente** [comment]
If your certificate is showing an alert you may have:

- **A self-signed certificate**: obviously if you have created the CRT and KEY by yourself, it won't be a valid certifiacte. You need to use one provided by a cert authority or thanks to technologies such as LetsEncrypt.
- **A wrong valid URL for the certificate**: if your certificate was created for a domain (www.sample-domain.com, for example) it will only be valid for that specific domain (and every subdomain).

That's the only scenarios where browsers complain about a certificate (well, it could be a valid but expired certificate too).

If you have an AWS account, you can check if your cert is a valid one with this [quick deployment guide](http://openvidu.io/docs/deployment/deploying-aws/#deploying-openvidu-server-on-aws-with-cloud-formation). You can deploy OpenVidu Server in 5 minutes on your domain with your own crt and key files, or you can simply let Let'sEncrypt generate a free, valid certificate for your domain.

Answering your last question, if you are working with real-time media over WebRTC, you should never use insecure websocket or http. Modern browsers only allow media streaming on secure webs. That's why OpenVidu documentation explains certificate issues: in the real world you will 100% need a secure web and a secure OpenVidu Server to have video streaming working.

**Comment by quickstreamingmedia** [comment]
how about making able to create lets-encrypt like aws can you give me clue to do that

**Comment by micaelgallego** [comment]
In our AWS machine, we use an NGINX server to configure certificate.

You can use any tutorial on how to use Let's encrypt with NGINX like this one:

https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by quickstreamingmedia** [comment]
my webserver is secured
but wss is showing its insecure response
![image](https://user-images.githubusercontent.com/6527923/32588679-030f7f2c-c543-11e7-812a-0fb48a37dc83.png)

**Comment by quickstreamingmedia** [comment]
i think, this is solved thanks i have created jks using letsencrypt certificate and it worked well

**Comment by athasamid** [comment]
@quickstreamingmedia can u give me clue to do it? I am using letsencrypt to, but didn't work
