### ISSUE TITLE
Java tutorial of KMS does not work on openvidu ec2 instance created with cloud formation.

### ISSUE THREAD

**Issue by philajay** [OpenVidu/openvidu#132]
Created an ec2 instance using instruction from [here](https://openvidu.io/docs/deployment/deploying-aws/). Openvidu dashboard works fine. Then I download the Java tutorial of Kurento and point them to KMS which was installed by installation above.  The loopback media of hello world does not play.  When I look at webrtc-internal logs of chrome , there are no errors and it shows that connection is established. However under ssrc_XXXX_rec  following information is logged
`

timestamp | 10/26/2018, 9:24:14 AM
-- | --
bytesReceived | 539961
codecImplementationName | unknown
framesDecoded | 0
mediaType | video
packetsLost | 245
packetsReceived | 628
ssrc | 3593867449
transportId | Channel-audio-1
googCaptureStartNtpTimeMs | 0
googCodecName |  
googContentType | realtime
googCurrentDelayMs | 0
googDecodeMs | 0
googFirsSent | 0
googFrameHeightReceived | 0
googFrameRateDecoded | 0
googFrameRateOutput | 0
googFrameRateReceived | 11
googFrameWidthReceived | 0
googInterframeDelayMax | -1
googJitterBufferMs | 0
googMaxDecodeMs | 0
googMinPlayoutDelayMs | 0
googNacksSent | 777
googPlisSent | 106
googRenderDelayMs | 10
googTargetDelayMs | 0
googTrackId | zTIQawyP

`

googcodecName is empty string but I can see the bytes received. I know that this is not openvidu issue per say, but I have been struggling with this issue for quite some time. Any help will be really apprceiated.

**Comment by micaelgallego** [comment]
In AWS instance created with CF the TURN server has one credential per user. For that reason, TURN server won't work without this specific credentials.

Why are you mixing things? OpenVidu CF is designed and tuned for OpenVidu client apps. Do you have any problem using OpenVidu? Why do you want to use Kurento examples?

**Comment by micaelgallego** [comment]
Thank you. Now I understand.

OpenVidu AWS Instance has OpenVidu-server, CORTURN and KMS. COTURN is configured in such a way that every client has to have specific credentials to connect to it. For that reason, OpenVidu apps work but plain Kurento apps don't. Because Kurento apps haven't configured TURN with specific credentials.

If OpenVidu suit your needs, use it as it provides a simpler programming model than plain Kurento. If OpenVidu doesn't suit your needs, then we will try to help you configuring Kurento Media Server.

In the last days we have published a new Kurento version. We have also published a new Kurento Cloud Formation. Please check it and tell us (in Kurento mailing list) if it is working for you.

**Comment by philajay** [comment]
Thank you. I will just try the new kurento version and will update this thread with the results.

**Comment by philajay** [comment]
I have tried to install kurento using the new kurento cloud formation three times and it works all the times.  
@micaelgallego  Thank you very much for your help.
