### ISSUE TITLE
Add custom video to stream from Publisher

### ISSUE THREAD

**Issue by SamKhachatryan** [OpenVidu/openvidu#155]
I have seen that stream's 'typeOfVideo' porperty can be "CUSTOM".
So how can I set custom video to stream from Publisher.

Thanks.

**Comment by pabloFuente** [comment]
As `typeOfVideo` entry says (https://openvidu.io/api/openvidu-browser/classes/stream.html#typeofvideo), whenever property `videoSource` is a MediaStreamTrack, it will be given "CUSTOM" value. You can easily get one with OpenVidu.getUserMedia (https://openvidu.io/api/openvidu-browser/classes/openvidu.html#getusermedia)

**Comment by SamKhachatryan** [comment]
Ok thanks, but is this returns the same with `navigator.mediaDevices.getUserMedia`?

**Comment by SamKhachatryan** [comment]
Please help me how to add custom video with url like
 https://www.w3schools.com/html/mov_bbb.mp4

**Comment by micaelgallego** [comment]
Have you looked this thread?

https://groups.google.com/forum/?nomobile=true#!topic/openvidu/uWBylN6RtfA

**Comment by micaelgallego** [comment]
The advices on it are not working for you?

**Comment by AngeSohone** [comment]
no no, i got stream camera in my HtmlElement, i used two token and two Openvidu session. One for camera stream and the second one for canvas. but canvas subscriber received camera stream instead of canvas drawing

**Comment by pabloFuente** [comment]
I need more info about your problem. I read your comments but I still don't have a clear idea of your particular scenario. Your are publishing 2 different streams to the same session by initializing 2 different OpenVidu objects (that's fine, this hack currently makes publishing more than 1 stream per client possible).

But when you publish both of them, you say your Subscribers receive the same stream belonging to one of the Publishers instead of receving the 2 different streams?

**Comment by AngeSohone** [comment]
> I need more info about your problem. I read your comments but I still don't have a clear idea of your particular scenario. Your are publishing 2 different streams to the same session by initializing 2 different OpenVidu objects (that's fine, this hack currently makes publishing more than 1 stream per client possible).
> 
> But when you publish both of them, you say your Subscribers receive the same stream belonging to one of the Publishers instead of receving the 2 different streams?

i just want to publish, stream from my canvas element. but when i setup videoSource with mediaStream Track, i got a strange result
1 - join session as a publisher, it's active my webcam
2 - Join session as subscriber, receive remote stream of publisher (his camera instead of his canvas stream)

this propriety can receive 3 types of values right?
- strting ('CAMERA' , 'SCREEN')
- MediaStream Track
- boolean

i used the second one (MediaStreamTrack), but look like is undefined and switch to camera
