### ISSUE TITLE
Error in Publisher.publishVideo() in case of multiple OpenVidu instances

### ISSUE THREAD

**Issue by neotericbyte** [OpenVidu/openvidu#172]
When creating single OpenVidu instance, Publisher.publishVideo() working fine. But I want to publish two streams one for Audio and another one for Video, So I have created two OpenVidu instances. In this case Publisher.publishVideo() giving an error from [Session.js, Line number 702](https://github.com/OpenVidu/openvidu/blob/1e46ca2287c5d8491b8f0dde940f9024059b4140/openvidu-browser/lib/OpenVidu/Session.js#L702). Please check the below error:

```Console
TypeError: Cannot read property 'emitEvent' of undefined
    at callback (Session.js:702)
    at Session.js:716
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:16156)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16147)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
```

For reference please check my code snipets:

```JavaScript
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { OpenVidu, Session, PublisherProperties, ConnectionEvent, StreamEvent, Publisher } from 'openvidu-browser';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

	private ovTokenAudio: string;
	private ovTokenVideo: string;
	private ovAudio: OpenVidu;
	private ovVideo: OpenVidu;
	private sessionAudio: Session;
	private sessionVideo: Session;
	private publisherAudio: Publisher;
	private publisherVideo: Publisher;

	@ViewChild('pAudio') pAudio: ElementRef;
	@ViewChild('pVideo') pVideo: ElementRef;
	@ViewChild('aButton') aButton: ElementRef;
	@ViewChild('vButton') vButton: ElementRef;

	public audioActive: boolean;
	public videoActive: boolean;

	constructor(
		private http: HttpClient
	) {
		this.ovTokenAudio = null;
		this.ovTokenVideo = null;
	}

	toggleAudio() {
		this.audioActive = !this.audioActive;
		this.publisherAudio.publishAudio(this.audioActive);
	}

	toggleVideo() {
		this.videoActive = !this.videoActive;
		this.publisherVideo.publishVideo(this.videoActive);
	}

	ngOnInit() {
		this.getToken('358').subscribe((res) => {
			this.ovTokenAudio = res.data.ovToken;
			this.ovAudio = new OpenVidu();

			this.sessionAudio = this.ovAudio.initSession();
			this.sessionAudio.connect(this.ovTokenAudio).then(() => {
				this.publisherAudio = this.ovVideo.initPublisher(
					this.pAudio.nativeElement, {
						publishAudio: true,
						publishVideo: false,
						videoSource: false,
					});
				this.sessionAudio.publish(this.publisherAudio);
				this.audioActive = true;
			}).catch((error) => {
				console.error(error);
			});

		});

		this.getToken('358').subscribe((res) => {
			this.ovTokenVideo = res.data.ovToken;
			this.ovVideo = new OpenVidu();

			this.sessionVideo = this.ovVideo.initSession();
			this.sessionVideo.connect(this.ovTokenVideo).then(() => {
				this.publisherVideo = this.ovVideo.initPublisher(
					this.pVideo.nativeElement, {
						publishAudio: false,
						publishVideo: true,
						audioSource: false,
					});
				this.sessionVideo.publish(this.publisherVideo);
				this.videoActive = true;
			}).catch((error) => {
				console.error(error);
			});

		});
	}

	getToken(sessionId): Observable<any> {
		const apiUrl = 'https://localhost:3333/api/openvidu/tokens';
		const params = {
			sessionId: sessionId
		};
		return this.http.post<any>(apiUrl, params, {
			headers: {
				token: '00a562182b1390b53e0ca8516c8a7ca24dd73e640100d0aace2918b198d0aefa'
			}
		});
	}
}
```

**Comment by pabloFuente** [comment]
This is due to your object **Stream** not having its property [streamManager](https://openvidu.io/api/openvidu-browser/classes/stream.html#streammanager) defined, which is something that should never happen. As you can see in this line:
https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/OpenVidu.ts#L221

`OpenVidu.initPublisher()` method will create a new **Publisher** object, which in its first line of the constructor (that is a call to `super()` of its parent class **StreamManager**, shared with **Subscriber** objects) creates its new **Stream** object:
https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/Publisher.ts#L75

**StreamManager** objects will always assing themselves as property `streamManager` of this newly created **Stream** object. Therefore, `Stream.streamManager` should never be undefined when Publisher object is properly initialized.

Maybe there's some problem with youur `this.pVideo.nativeElement` obect. Try debugging your javascript code setting breakpoints here https://github.com/OpenVidu/openvidu/blob/1e46ca2287c5d8491b8f0dde940f9024059b4140/openvidu-browser/lib/OpenVidu/Session.js#L702 and here https://github.com/OpenVidu/openvidu/blob/1e46ca2287c5d8491b8f0dde940f9024059b4140/openvidu-browser/lib/OpenVidu/StreamManager.js#L53 to analyse why `streamManager` property of the Stream of your video is not defined.

**Comment by krish-dev** [comment]
@pabloFuente I have also faced the same issue as @NeutralBuild described.

**Comment by pabloFuente** [comment]
Any news on this issue? In release 2.9.0 we implemented multiple Publishers in our [openvidu-call](https://github.com/OpenVidu/openvidu-call) application, and we didn't found this problem. If you have more information, please reopen it. You can also try upgrading to a more recent version to see if it fixes the problem.
