### ISSUE TITLE
Errors when kms restarts

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#174]
Hi!
We have detected that when the kms is restarted, the openvidu-server does not reconnect correctly with it. We have tested this with the docker image of openvidu-server-kms as well as with separate containers (openvidu-server container and kms container), like manually launching them on my machine. The behavior is as follows, the kms is restarted, the openvidu-server reconnects with the websocket, but the video streams are not generated, they remain empty, both those who were already in a session when the kms fall as the new flows of new sessions created after. The error it gives is "MEDIA_OBJECT_NOT_FOUND", I attached capture of said error. To fix it I had to restart the openvidu-server, because as I said before the video streams are empty, without flow. I would like, if you can, to give you an eye or on the contrary tell me where you can capture this error to restart the server or make a new connection with the kms. Thanks in advance!

![image1](https://user-images.githubusercontent.com/17248343/51168269-0ab9d000-18a9-11e9-810c-c350e26b151e.png)

**Comment by pabloFuente** [comment]
Hi!

Currently there's no official way of knowing when openvidu-server has unexpectedly disconnected from KMS. It is of course possible, and we have just implemented it in openvidu-server in a quick refactoring, but the problem is more of an API issue: this should be notified to some endpoint so devs can listen to the event.

So, this will be added as a backend event when they are added to OpenVidu platform (hopefully not too long from now). We intend to provide a very simple mechanism for which users can specify an HTTP endpoint (where their application server should be listening), and OpenVidu will send events to that endpoint in the form of a POST operation whenever they are generated. This way developers would be able to have every important event regarding sessions in their server side, just as clients do right now. But also other interesting events not too important for the client side but for the server side: KMS disconnected, KMS reconnected, WebRTC media cuts for specific streams.....

As a quick solution for you, you could implement your own loop mechanism to listen to KMS process as a system service, checking that it is up and running. That shouldn't be too complicated and you can adapt it to best fit your framework/environment.

Regards

**Comment by pabloFuente** [comment]
By the way, the error you stated only happens for sessions that where taking place when KMS crashed and then try to perform actions after reconnecting to it. After OpenVidu Server has automatically reconnected to KMS (that should take 5 seconds), any new established Session will work fine.

**Comment by miguelrcDEV** [comment]
Not exactly. If I stop kms container, wait 5seconds, start kms container again, wait for openvidu-server to reconnect to them. After this any new session has empty flush streams.

**Comment by pabloFuente** [comment]
That's not the behavior I'm getting. If a stop KMS for 5 seconds and start it again, I'm able to start new sessions and new users can send and receive video fine. Just tested this and it works ok. What version of OpenVidu are you using?

**Comment by miguelrcDEV** [comment]
I'm using Openvidu v2.7.0 in a docker container. My kms is also in a docker container in v.6.9.0 . Like I told you, when stop kms container, then start and wait to openvidu-server to reconnect, after this any new stream throw the "MEDIA_OBJECT_NOT_FOUND" error in openvidu-server.
Thanks in advance Pablo.

**Comment by pabloFuente** [comment]
I was trying in a non-docker environment (KMS installed in my machine and openvidu-server run as a Java process, as explained [here](https://openvidu.io/docs/deployment/deploying-ubuntu/))

Why do you have OpenVidu and KMS in separate images?  `openvidu/openvidu-server-kms` docker image has everything you need in a single container. At least for development purposes (Docker is not supported for production environments)

**Comment by miguelrcDEV** [comment]
With the openvidu/openvidu-server-kms docker image I have the same error like I told you in the previous comment. I'll try with a non-docker environment then, checking if has this same error.
Thanks!!

**Comment by pabloFuente** [comment]
If you use openvidu-server-kms container, then you really shouldn't have any ohter container running and of course no KMS process up and running in the host. Using that container you really cannot stop KMS unless you get into the container and stop the process inside of it.
I tell you this because I'm missing somehting in your setup.

- Or you have KMS natively installed as a service and running in your machine (Ubuntu Xenial) and you start openvidu-server Java process.
- Or you run `openvidu-server-kms` docker container and do nothing else. No other container, no KMS as a native process, no openvidu-server Java process.
