### ISSUE TITLE
Select source stream

### ISSUE THREAD

**Issue by HeriBrito** [OpenVidu/openvidu#18]
Hi,

i have some input video streams (webcam, hdmi, etc), so how can i select the source stream when call OV.initPublisher?, one is selected, but i don't know whats criterie is follow. Thank you again.

Regards,
Heri

**Comment by pabloFuente** [comment]
Hi,
You will be able to select the desired audio and video source on `OpenVidu.initPublisher` method. This feature will be available in the near future.

**Comment by sandeep048** [comment]
Hi,

We desperately need the ability to select camera and microphone options on the WebRTC video call. Can we get this device selection functionality to take effect immediately in the video conference?
Just reiterating the immediate need of this functionality.

Regards,
Sandeep

**Comment by micaelgallego** [comment]
Hi Sandeep,

We are a small team working on OpenVidu and Kurento. We prioritize the most
useful features for the most of users.

If you have a request for a very specific feature, we offer commercial
support to implement it.

Please contact with openvidu@gmail.com for details.

Regards

El 24 feb. 2018 11:39, "Sandeep Pathivada" <notifications@github.com>
escribió:

Hi,

We desperately need the ability to select camera and microphone options on
the WebRTC video call. Can we get this device selection functionality to
take effect immediately in the video conference?
Just reiterating the immediate need of this functionality.

Regards,
Sandeep

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenVidu/openvidu/issues/18#issuecomment-368219055>,
or mute
the thread

**Comment by sandeep048** [comment]
Sure we will get back. Thank you.

**Comment by sandeep048** [comment]
I got it. We can have an event handler similar to the code snippet below for switching between available cameras/microphones etc.

```
$("#camselect").on("change", function() {
	session.unpublish(publisher);
	var deviceId = $("#camselect :selected").val();
	publisher = OV.initPublisher("publisher", publisherOptions);
	publisher.stream.outboundOptions.mediaConstraints.video.deviceId = {
	  exact: deviceId
	};
	session.publish(publisher);
});
```

Is it possible to select output speakers/headphones?

Regards,
Sandeep

**Comment by sandeep048** [comment]
ahh got it. audio output can be configured using video.setSinkId API.

```
element.setSinkId(sinkId)
.then(function() {
  console.log('Success, audio output device attached: ' + sinkId);
})
.catch(function(error) {
  var errorMessage = error;
  if (error.name === 'SecurityError') {
    errorMessage = 'You need to use HTTPS for selecting audio output ' +
        'device: ' + error;
  }
  console.error(errorMessage);
});
```

**Comment by pabloFuente** [comment]
Hi,

OpenVidu 2.0.0 now allows selecting device inputs and much more. You can check out the new API in the [reference documentation](https://openvidu.io/api/openvidu-browser/).
