### ISSUE TITLE
Recompile openvidu

### ISSUE THREAD

**Issue by sanket044** [OpenVidu/openvidu#188]
Hello,

I am doing screen sharing tests, and wanted to take whole openvidu version offline. But i found that open vidu goes to openvidu.github.io to take one scrip. "openvidu/openvidu-browser/static/js/openvidu-browser-2.7.0.js" line no 7485.

I changed that link with local address, and tried to compile using following code.

git clone https://github.com/OpenVidu/openvidu.git
cd openvidu
mvn compile -Dskiptests=true
mvn install -Dskiptests=true

Still it goes to web instead of local address. I am using following command to start the openvidu server.

sudo docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://192.168.0.1:4443 openvidu/openvidu-server-kms:2.7.0

 Any help?

**Comment by pabloFuente** [comment]
Hi,

When you say `"But i found that open vidu goes to openvidu.github.io to take one scrip. "openvidu/openvidu-browser/static/js/openvidu-browser-2.7.0.js" line no 7485"`

What do you mean about "openvidu goes to openvidu.github.io to take one script"? What exact line has a link to that file, and in which artifact?

**Comment by sanket044** [comment]
I have already mentioned file and line number. Openvidu-browser.js goes to take one java script file for screensharing.

**Comment by pabloFuente** [comment]
Yes. In fact openvidu-browser loads that file to allow screen-sharing in Chrome because it is a way of making [OpenVidu Screen Sharing extension](https://chrome.google.com/webstore/detail/openvidu-screensharing/lfcgfepafnobdloecchnfaclibenjold?hl=es) to work **on any domain**.
Screen sharing extensions for Chrome need to have specific domains declared in their manifest.json, as you can see [here](https://github.com/OpenVidu/openvidu-screen-sharing-chrome-extension/blob/master/extension/manifest.json#L17).

The "hack" of loading that file in an iframe (that's what you can see in line 7485 of openvidu-browser.js) makes possible to have only one extension that will work on any domain.

So, 2 things:

- File "openvidu-browser-{VERSION}.js" available [here](https://github.com/OpenVidu/openvidu/tree/master/openvidu-browser/static/js) is already compiled and ready to use. Whatever change you do inside of it will have immediate effect in a web application that uses that file. The commands you stated above to compile OpenVidu are meant to compile OpenVidu Server, not OpenVidu Browser.
- I'm not sure what will happen if you change the the url of line 7485, but probably you will break the use of the extension. If you really need to have everything locally in your dev machine, the best thing is that you create your own extension following the simple steps explained [in this README](https://github.com/OpenVidu/openvidu-screen-sharing-chrome-extension) and use thtat extension instead.

**Comment by sanket044** [comment]
Actually, i have tried to do it by host entry and redirecting that url to my apache server and it works perfectly. But i am using docker command to run the openvidu server, which is jar file containing everything. I am not sure where to find this js file in my system.

**Comment by pabloFuente** [comment]
`I am not sure where to find this js file in my system`: You should have openvidu-browser.js file wherever your web application making use of OpenVidu is stored.
OpenVidu Server  just needs to be run and know its IP address.

**Comment by sanket044** [comment]
Sorry, i was on wrong path. Thank you for help.
