### ISSUE TITLE
openvidu certification warning

### ISSUE THREAD

**Issue by sourabh947** [OpenVidu/openvidu#189]
![openvidu](https://user-images.githubusercontent.com/38677230/52113694-0a069500-2630-11e9-8a3c-460d9cea9344.png)
if i clike join then give like this .
I check "https://  .  .  .  :4443"   individually then it's working . if i check with UI then it's not showing any anything.

**Comment by pabloFuente** [comment]
This happens when there's an insecure certificate in openvidu-server. You have to navigate to your openvidu-server url (https://138.197.200.116:4443/ in the image above) to accept it, so Chrome remebers next time and let you connect to it.
Of course for a production environment you will need a valid certificate. With it you will not get this error.
