### ISSUE TITLE
Stream gets unavailable due to fixed video parameters?

### ISSUE THREAD

**Issue by PaulNicolasHunter** [OpenVidu/openvidu#196]
I'm trying to make a broadcast app, and as there is no direct doc to it, what I'm doing to achieve that is by calling **OV.initPublisher** only for certain clients, and `mySession.once('streamCreated', (event) => {))` for other clients.

however, I'm facing some issues that when there is 3 or more sessions, the stream on the clients of either of the session gets disconnected.. (**we were testing it on a network to which we were connected remotely through a VPN**)
so suppose we have 4 sessions created by 4 people and every other person is connected to the rest three.. 

And in other case we have two publishers, and the rest two are connected to the two publishers.

so, what I assumed that it is because of fixed frame rate and resolution of the publisher stream, and what happens that **openvidu** tries to maintain that frame-rate and just gets disconnected or just gets stuck when the network capability is not able to do so, these are my parameters..

```
{
     audioSource: undefined,
     videoSource: undefined,
     publishAudio: true, 
     publishVideo: true, 
     resolution: '1280x720',
     frameRate: 35,
     insertMode: 'APPEND', 
     mirror: false, 
}
```
So, what workaround I'm thinking is that continuously monitoring the network **UPLOAD** speed from the publisher and altering the resolution and frame-rate parameter accordingly, by doing a little math.

like in the parameters rather than      
```
    ... 
     resolution: '1280x720',
     frameRate: 35,
    ...
```
we get the upload speed of the publisher and choose the ideal resolution as we know the size of one frame of a resolution.. and then similarly finding the frame-rate
```
    ... 
     resolution: IdeaResolution(), // returns the ideal resolution
     frameRate: IdealFrameRate(), // returns the ideal frame-rate
    ...
```
from the subscriber perspective, I'm doing the same thing but there I'm monitoring **DOWNLOAD**, but the problem is that on subscriber end there are no parameters to alter, I just have to accept the stream as it was published (**or I'm just unaware of such method**)

my question is that: Is there a method to selectively accept the remote stream ? or we just can accept as it is being published.

**Comment by pabloFuente** [comment]
Simulcast is what you are looking for. Unfortunately, it is not available in OpenVidu yet. It is on our mid-term roadmap, but it will suppose tons of work and refactoring.

In the meantime, you can tweak streams bandwitdh globally in OpenVidu Server by using [system properties](https://openvidu.io/docs/reference-docs/openvidu-server-params/):

- `openvidu.streams.video.max-recv-bandwidth`
- `openvidu.streams.video.min-recv-bandwidth`
- `openvidu.streams.video.max-send-bandwidth`
- `openvidu.streams.video.min-send-bandwidth`

You can also adjust these properties for each client connection when generating their token. See `kurentoOptions` parameter on https://openvidu.io/docs/reference-docs/REST-API/#post-apitokens

Changing these values dinamically is not really supported. That is were simulcast will come into play. Changing video quality in the Publisher side may help in your case, but the problem is that framerate and resolution are constant once you access your input device with them (and they are only met for certain browsers. For example, firefox will only accept specific resolutions and framerates if the webcam itself natively support them in the hardware layer. Chrome is able to twek resolution and framerate with software). So, I would not rely on dynamically changing video stream quality properties on the publisher's client side.

Finally, we have included in our roadmap support for RTSP and HLS in the future, so live broadcast streaming for massive conferences will be available through these protocols for better performance.

**Comment by PaulNicolasHunter** [comment]
Thanks for the quick replies Mr. Pablo and yea I'm desperately waiting for those major updates and I'm sure you guys are working hard for it too..

maybe then we can achieve something like YouTube which dynamically sets the resolution according to the network connection.

meanwhile, what do you think could be the reason for the stream to just disappear from the client side? 
any workaround to it?

What do you think are the best practices to follow ( also in the context of **screen sharing**) for best results?

**Comment by pabloFuente** [comment]
Regarding performance, I really recommend to you this post we published a few weeks ago:

https://medium.com/@openvidu/openvidu-load-testing-a-systematic-study-of-openvidu-platform-performance-b1aa3c475ba9

As you will see in the article, OpenVidu Server performance varies depending on the specifications of the server hosting it, obviosuly. But for 1:N sessions it should behave well for a fair amount of streams. See If you can find errors in openvidu-server logs when your connections drop. Also you can monitor your server to see the CPU usage, especially when you start to see connection faliures. That way you'll be able to discard this to be a server-lack-of-resources issue.

**Comment by PaulNicolasHunter** [comment]
thanks for this intuitive mail blog-post.. really looking forward for OpenVidu towards an exponential growth..

a quick question, is there any chance that OpenVidu will opt-in for Gsoc this year?
I would love to be a part as a student.

**Comment by PaulNicolasHunter** [comment]
well that's sad, I really look forward next year to OpenVidu.
thanks again for help
