### ISSUE TITLE
Getting wrong sessionID while using remote VM

### ISSUE THREAD

**Issue by blcktqq** [OpenVidu/openvidu#21]
Good day!  
I deployed OpenVidu app using docker to Azure VM.
When i try to generate SessionId, i'm getting "wss://localhost:8443/i7kgub9b02dh95vfvgu5kg75rl",
which not work further on my app, because i didn't run OpenVidu server locally. How can I fix it?
I used this command 
`
sudo docker run -d -p 8443:8443 -e openvidu.secret=YOUR_SECRET --net="host" openvidu/openvidu-server
`

I tried change --net  to bridge, but it throws exception.

**Comment by pabloFuente** [comment]
Hi:

In order to change the URL that will be part of Server IDs, you just need to add a new variable on launch:
`-e openvidu.publicurl=https://YOUR_PUBLIC_ACCESIBLE_URL:8443/`
Remember that this is the URL where all websockets will be connecting from the client side. So it must be properly binded to your OpenVidu Docker container.

Regards.
