### ISSUE TITLE
Disconnection reconnection mechanism

### ISSUE THREAD

**Issue by ly3299297** [OpenVidu/openvidu#223]
If some unexpected reasons, such as the network, drop the line, how do you deal with it? Do you have your own disconnection and reconnection mechanism? If so, what is it?

**Comment by pabloFuente** [comment]
Every client connected to OpenVidu Server has a ping-pong mechanism. If OpenVidu Server detects that some user has unexpectedly dropped his connection by using this mechanism (10~15 seconds approx), it will terminate its connection and clean all entities associated to it. Every other user connected to the same session will receive the appropriate events once this is done (streamDestroyed, connectionDestroyed, .... All of them with reason `networkDisconnect`, so they know the user was evicted because his connection dropped).

For now we suppose that if users drop their connections, then all their received media streams will also freeze, and also the subscribers of other users receving their streams (this could not be the case for more advanced setups, where OpenVidu Server and Kurento Media Server are not hosted in the same network. In this case users could lose their connection to OpenVidu Server but keep their connection to the media server, keeping the webrtc connections alive). If the connection is restored before the ping-pong process evicts the participant, then the user is considered "reconnected".

In our tests, desktop browsers behave really well during these reconnections. WebRTC streams are automatically restored without any renegotation process needed, so the reconnected user simply sees how their subscribed streams start playing again and other users will see the published stream of the reconnected user unfreeze. Mobile browsers seem to be somewhat less functional in this respect. They are not usually capable of restoring their WebRTC streams, so videos will no unfreeze if a mobile client is the one losing its connection.

**Comment by beyondlevi** [comment]
Any clue in how could unfreeze streams? Witch callback or propertie should be used to check if a specific stream is frozen?

**Comment by pabloFuente** [comment]
Hi, check this out: https://docs.openvidu.io/en/stable/advanced-features/automatic-reconnection/
Since release 2.12.0 automatic reconnection of frozen streams caused by a network drop in the client side is provided out-of-the-box.
