### ISSUE TITLE
KMS restart event to openvidu-browser

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#232]
Hi! It's posible get an event on openvidu-browser like "sessionDisconnected" with reason "kmsRestarted"?

I propose this because, when kms restart in middle of a videoconference, is necessary reload client to continue with videoconference successfully. If we get the event that I commented before, we can reload by code the client page, or rejoin to continue the videoconference.

**Comment by pabloFuente** [comment]
You will receive events `streamDestroyed` with reason `mediaServerDisconnect` if a reconnection of KMS takes place. Every user connected to the session will receive it so they know that the streams will be frozen because of the reconnection (https://openvidu.io/api/openvidu-browser/classes/streamevent.html#reason)
Event `recordingStopped` will also be triggered with this reason if the session was being recorded while KMS disconnected (https://openvidu.io/api/openvidu-browser/classes/recordingevent.html#reason)
