### ISSUE TITLE
Concat recording if file exist

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#28]
Right now, if a session that is being recorded is empty (0 participants), and after a while a participant re-enters that session, the recording that was there is erased and starts from zero. It would be possible to have it concatenated if the file exists?

**Comment by pabloFuente** [comment]
The problem is that if all participants leave a Session, the Session is destroyed.
I mean, you can manage the Session as the same entity in your business logic, but for OpenVidu the Session is closed and no longer exists whenever all participants leave it.

I guess you are creating your session from your client (building by hand the sessionId like the first point [here](http://openvidu.io/docs/troubleshooting/#5-what-are-the-differences-related-to-openvidu-between-an-app-without-a-server-side-and-an-app-with-a-server-side)) and that you keep naming the session the same when a user re-enters the Session:

```javascript
var session = OV.initSession("wss://YOUR_IP:8443/MY_VIDEO_SESSION?secret=MY_SECRET");`
// If you call again this line without modifying "MY_VIDEO_SESSION", the recording will be overwritten.
```

For OpenVidu, the second time you call that line a new completely different Session is created. If you were making use of the API REST the sessionId would be completely different and no collisisions would take place. But you are not getting sessionId's and tokens from OpenVidu Server, but building them by hand in your JavaScript code. I guess the sessionId that you are sending remains the same when you create the new Session, and the problem is that it is also used to name the video file and overwrites the previous one.

This is a behaviour that we will fix soon, because the file should never be overwritten but renamed (or maybe with a timestamp in the name). But let me encourage you to add a backend to your application (if it has none) and to make use of the API REST of OpenVidu Server (or openvidu-java-client / openvidu-node-client if your application's backend is Java / Node) to securize your video sessions and to get rid of this issues of managing the session ids from your JS code.

**Comment by pabloFuente** [comment]
With the last update of [openvidu-recording](https://hub.docker.com/r/openvidu/openvidu-recording/tags/) Docker image, now video files are never overwritten. If there's already a file equally named in the recording path as the new file that's gonna be created, the new file will be named appending a number at the end.

For example, if a video file `video.mkv` already exists, the new file would be automatically named `video(1).mkv`. If this exists too, the new file would be `video(2).mkv`, and so on.
