### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by miptildar** [OpenVidu/openvidu#305]
I am looking for a WebRTC library that is suitable for using in production/real-life. I was considering using OpenVidu in my future startup project. But I need to clarify one moment.
It is enough to have a `server secret` to connect to OpenVidu servers. Doesn't it create vulnerabilities, because if the `Secret` gets leaked anyone gets access this service?

How could I secure the system? Can I add custom authorization?

**Comment by micaelgallego** [comment]
As mentioned in the docs (Get a token from OpenVidu Server section in https://openvidu.io/docs/tutorials/openvidu-hello-world/ for example). You need a backend application to maintain server secret secure. We provide a lot of client-side only applications because they are easy to test and hack. But all of them have a warning indicating what part of the code should be moved to backend.

In fact, you have a sample app using Java as backend and another using Node. But your backend app can be implemented with any lang as OpenVidu Server provides a REST API to create tokens for participants.
