### ISSUE TITLE
Momentary Disconnection when switching on screen sharing.

### ISSUE THREAD

**Issue by wardhanster** [OpenVidu/openvidu#307]
There is a momentary disconnection (loss of both audio and video) when one of the users start a screen share session, given that the user joined the room with `video:false` constraint.

**Comment by pabloFuente** [comment]
The user does not join a session with `video: false` property. In fact, there is not such an option in OpenVidu Browser API. Please, be as exact as possible when defining an issue, because otherwise I will have to guess what your problem is and I may fail doing so.

Users may initialize Publisher objets with `videoSource: false` property or with `publishVideo: false`. First one means that the internal WebRtc outgoing stream will be audio only. Second one that there will be a video stream, but it will start muted.

OpenVidu does not allow right now to change on the fly the tracks of an already established WebRTC peer connection. That means that a Publisher initialized with `video:false` cannot start publishing a screen. A new Publisher object must be initialized, and then you can proceed unpublishing the old one and start publishing the new one. This unpublish-publish process can be optimized to reduce the time there's no stream being sent by using the API callbacks, but maybe it can't be completely avoided. You can take a look to our OpenVidu Call demo (https://demos.openvidu.io/openvidu-call/#/) and see how it behaves regarding this issue.
