### ISSUE TITLE
how to use cordova plugin enumeratedevices?

### ISSUE THREAD

**Issue by ar1stio** [OpenVidu/openvidu#314]
i try to add cordova plugin enumaratedevices but , its not available in npm

**Comment by pabloFuente** [comment]
Hi,

This plugin is not uploaded as an artifact of OpenVidu platform because it is not stable. It was an attempt to simplify the enumeration of inputs/outputs in Android cordova applications, but due to limitations in the API it is not possible to return a standard result (the issue was in fact related to the labels of the devices).
