### ISSUE TITLE
crash on the review test

### ISSUE THREAD

**Issue by githubbla** [OpenVidu/openvidu#329]
I found comparison test of many media servers, there strange things they unable to test openvidu to more than 150 sessions? Does this issue fixed? 

[https://webrtchacks.com/sfu-load-testing/
](https://webrtchacks.com/sfu-load-testing/
)

**Comment by pabloFuente** [comment]
Hi,

We developed time ago a load testing platform for OpenVidu. You can read the complete article here: https://medium.com/@openvidu/openvidu-load-testing-a-systematic-study-of-openvidu-platform-performance-b1aa3c475ba9.

The study you appended was in fact the reason we implemented this test suit. There were a couple of things of that study that affected OpenVidu performance. That said, it is true that Kurento is a heavier process than other media servers. This makes it, on the one hand, less recommended for scenarios with massive videoconferences. But it works correctly in all use cases that do not require 500 simultaneous users connected to the same video sesssion, and offers other interesting features that do not have media servers whose only functionality is the flat transmission of media packages, such as automatic transcoding or audio and video filters in real time.

We know our limitations right now, and that's why we're working to support other open-source media servers, more focused on mass video conferencing support. The idea is that users will be able to choose the ideal media server for each scenario at runtime, without having to change the code of their application at all. The following months will be interesting!
