### ISSUE TITLE
How to get an event if a user leaves the hangout

### ISSUE THREAD

**Issue by hazratgs** [OpenVidu/openvidu#334]
Greetings guys, we use OpenVidu Browser, we need if during the meeting, someone either closes the tab or just turns off their computer, receive an event from another user and end the video connection.
Now if 2 users communicate and one closes the tab, the second user just sits and sees a black screen, we need to get the event that the other has disconnected and stop the video consultation.

I looked at the documentation, did not find the appropriate method, please indicate the implementation method

Thanks everyone

**Comment by pabloFuente** [comment]
If a user unexpectedly leaves the session, every other user will be warned whenever openvidu-server detects that the user is no longer connected to it. When does this happen? When the ping-pong mechanism that every user internally establishes with openvidu-server fails. That usually takes some seconds.

When openvidu-server does not receive ping from the user, sends a `streamDestroyed` even (if the user was publishing) and a `connectionDestroyed` event to every other participant in the session. The `reason` parameter will be `networkDisconnect` (so that's the way you know the user disconnected because openvidu did not receive ping from it, not because it explicitely called `Session.disconnect` method)

If i were you I'll always try to send the proper `Session.disconnect` method on standard web listeners such us window.onbeforeunload or window.onunload. Many times the browser is capable of calling those methods even when the user closes the window or refreshes the page, and that way all other participants will receive the destroyed events immediately and not after a few seconds.
