### ISSUE TITLE
checkSystemRequirements does not detect compatible Samsung browsers.

### ISSUE THREAD

**Issue by wardhanster** [OpenVidu/openvidu#361]
Hi, 
we are now using OpenVidu in production with a slight annoyance of that it does not detect Samsung browser is webrtc compliant or not. Even though it is.
In another case, it returns true for some of the latest Xiaomi phones. When I looked into the code it seems like the tests are done based on user-agent and not the availability of the actual API in the browser?
Any particular reason why it was done that way?

**Comment by pabloFuente** [comment]
Sure. Because supporting the WebRTC  MediaStream and RtcPeerConnection API is a necessary but not sufficient condition for establishing media connections with OpenVidu Server. As you may already know, WebRTC and SFUs are very complex technologies with many layers involved: networking, codecs, performance.... We cannot directly officially support in openvidu-browser all clients which API is supposedly compatible with WebRTC API. We must perform other kind of tests and inter-compatibility checks, and of course ensure their well-functioning over time. So, that's the reason developers should only trust these clients when using OpenVidu: https://openvidu.io/docs/troubleshooting/#8-what-platforms-are-supported-by-openvidu

Either way, try changing openvidu-browser yourself to test Samsung's browser and post here if it did worked well. You can compile openvidu-browser following these instructions: https://openvidu.io/docs/developing/#compiling-openvidu-browser

Closing the issue for now.
