### ISSUE TITLE
Axios lib error function toJSON

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#369]
**Describe the bug**
Using openvidu-node-client lib, when status code response of request is not 200, axios libs throw error "error.toJSON" is not a function, and this make node server go down.

**Expected behavior**
Return code error

**Wrong current behavior**
Throws an uncaught error and make node server go down.

**OpenVidu tutorial where to replicate the error**
Start recording in a session that is already being recorded

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` ubuntu server 18.04

**Screenshots**
![image](https://user-images.githubusercontent.com/17248343/71176445-33d9a200-226a-11ea-8108-8c8944cf276d.png)

**Comment by pabloFuente** [comment]
Hi,

The description of the bug is incomplete. Or at least I'm not capable of replicating the problem. Try [openvidu-recording-node tutorial](https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-recording-node) and start the recording of a session already being recorded. No fatal error occurs at all. The code managing the recording start process is this:

```
OV.startRecording(sessionId, recordingProperties)
        .then(recording => res.status(200).send(recording))
        .catch(error => res.status(400).send(error.message));
```

This just fails as expected: if trying to initialize a recording already started, then openvidu-node-client lib fails the promise and the `catch` block will be executed, in this case with a 409 error.

I'm closing the issue in the meantime. The bug cannot be just "openvidu-node-client lib is throwing an exception when trying to start the recording of a session already being recorded", because that doesn't happen. If you describe in more detail the problem you have (some sample code may help), we can take a look at it.
