### ISSUE TITLE
Always-On Video Suggestion

### ISSUE THREAD

**Issue by Bigben83** [OpenVidu/openvidu#380]
This looks like a great platform, has anyone tried it for always-on video conferencing between two remote offices.

I have looked at the following website, and Im sure something like this would be easy to implement. 
[videowindow.com](https://videowindow.com/)

**Comment by pabloFuente** [comment]
Yes, this kind of use case is perfectly possible with OpenVidu. In fact it can be as simple as a 1:1 video conferencing room. You can start with any of the available [tutorials](https://openvidu.io/tutorials).

I'll close this post now, because GitHub issues are only intended for possible bugs or problems with OpenVidu source code. For any other kind of question, please consider visitting OpenVidu forum: https://openvidu.discourse.group/

**Comment by Bigben83** [comment]
Thanks heaps @pabloFuente 
I have created a separate git for an always-on app, in case anyone wants to see the idea.

[https://github.com/Bigben83/openvidu-always-on](https://github.com/Bigben83/openvidu-always-on)
