### ISSUE TITLE
Recording share screen can not connect remote audio

### ISSUE THREAD

**Issue by HeroTran** [OpenVidu/openvidu#385]
I have an issue when I share screen recording 2 brower( video call) I can not connect remote audio and I can not hear anything from brower connect .
Please let me know How can connect remote audio when recording share screen brower

**Comment by pabloFuente** [comment]
Hi,

Please, describe your problem in more detail. We know the bug report template is long, but it is so to make us easier to better understand developers issues. Could you please fill the report as it is provided? That way we'll be able to give you a complete answer and your problem is more likely to be solved.

Thanks.

**Comment by HeroTran** [comment]
Hi pabloFuente, 
![Capture](https://user-images.githubusercontent.com/10969446/74143450-692cbb80-4c2d-11ea-8e7c-3b329eb7e3d9.PNG)
  So Sorry
I want to recording screen broswer during video call,
I using 
const publisher = OV.initPublisher(undefined, {
          audioSource: undefined, // The source of audio. If undefined default microphone
          videoSource: 'screen', // The source of video. If undefined default webcam
When I call video with my friend on browser,I want to recording all behavios and sound the both I and my friend,
I have an issue ,When recording done and create new video on server.I just hear sound from my side, can not hear from My friend's side.
How Openvidu recording and remote audio the both.
Thanks

**Comment by pabloFuente** [comment]
I still lack information about your scenario. What kind of recording are you trying to do? COMPOSED recording or INDIVIDUAL recording? Are you sure you are starting the recording with video and audio options set to true? Are both streams initialized in the browser with the code you stated above? Are you able to hear the remote audio, but the recording file does not have audio?

Maybe you have some sample application we can test to see if there's some kind of issue? Because recording with screen share and audio is working fine in our testing environment.

**Comment by HeroTran** [comment]
Hi Pablo Fuente Pérez ,
Many thank your support, I really appreciate
This is my mistake, I test on local environment, It doesn't working
I try to test on production and it work perfectly
Thanks.

**Comment by HeroTran** [comment]
Hi Paolo
When I run app openvidu in locahost and share screen & recording other
browser (video call & camera) that video has recording work very well can
hear the both user
But When deploy it on production and share screen active browser &
recording I just hear from my side , not able to hear from other user.
https://record.1on1english.vn:4443/recordings/81defa9b-2bf7-41d7-917b-e19bfbef79b9-18/81defa9b-2bf7-41d7-917b-e19bfbef79b9-18.mp4

I don't know why, many be releted my server
