### ISSUE TITLE
Compilation error in build pipeline

### ISSUE THREAD

**Issue by Ebalon09** [OpenVidu/openvidu#401]
./node_modules/openvidu-browser/lib/OpenViduInternal/KurentoUtils/kurento-jsonrpc/index.js
 TypeError: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null

**Comment by pabloFuente** [comment]
Can you extend your issue? When do you exactly get this error? How can we replicate it? Issue template is there to facilitate the process of helping users with possible bugs.

**Comment by Ebalon09** [comment]
The issue occurs when deploying my application via a gitlab pipeline. I build a docker container in which i clone my project an then install all dependencies. When compiling the pipline exits with the given error.

The pipeline executes a npm run build step. when executing this step manually in my local project the same error occurs. When executing npm start the error does not happen.

**Comment by wearebear80** [comment]
+ same problem

**Comment by hazratgs** [comment]
same problem

**Comment by pabloFuente** [comment]
We have not encountered this issue in any of our CI pipelines. Seems a problem with Babel, as @hazratgs mentoined: https://github.com/babel/babel/issues/11231. Since that issue is already closed and a month has elapsed since this one was created, we are gonna assume that this problem is currently solved.  If anyone is still having problems to to compile openviud-browser, please comment below.
