### ISSUE TITLE
couldn't setup both TURN and STUN servers in docker openvidu/openvidu-server-kms 

### ISSUE THREAD

**Issue by isergey87** [OpenVidu/openvidu#41]
we run docker with "... -e KMS_STUN_IP=$STUN -e KMS_STUN_PORT=$STUN_PORT -e KMS_TURN_URL=$TURNURL ..."

But WebRtcEndpoint.conf.ini in container containes only stunServerAddress and stunServerPort

In kms.sh 
"echo "stunServerAddress=$KMS_STUN_IP" >" replace TURN URL

**Comment by pabloFuente** [comment]
I have just tested it and you are totally right. In fact there's a bug which is pretty clear:

In [this line](https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/docker/openvidu-server-kms/kms.sh#L10) the command should be

`echo "stunServerAddress=$KMS_STUN_IP" >> ... `
and not
`echo "stunServerAddress=$KMS_STUN_IP" > ... `

becuase STUN configuration is overriding the previous TURN configuration. So providing both in docker command will end with no TURN configuration at all.

Thanks for opening the issue. This will be fixed in release 2.0.0, which will take place in the following days.

**Comment by pabloFuente** [comment]
OpenVidu 2.0.0 fixes this bug
