### ISSUE TITLE
OpenVidu Docs page is down - 404 Not Found

### ISSUE THREAD

**Issue by MeteC** [OpenVidu/openvidu#430]
- Click https://openvidu.io/docs/home
- See 404 Not Found error. "The site configured at this address does not contain the requested file."

(Seen Sunday 12 Aprl and today Monday 13 April)

**Comment by pabloFuente** [comment]
Since a week ago documentation was moved to https://docs.openvidu.io/
We announce it in differente channels:
https://twitter.com/openvidu/status/1247116019132489733?s=20
https://openvidu.discourse.group/t/new-openvidu-documentation/414
Also all links to the docs in openvidu.io have been updated to point to docs.openvidu.io. Now it is just a matter of time for Google to update its links to the new domain.

**Comment by MeteC** [comment]
Ah ok thanks - note the old link is still referenced here: https://github.com/OpenVidu/openvidu/wiki

**Comment by pabloFuente** [comment]
Already updated. Thank you for reporting.
