### ISSUE TITLE
Audio unmutes on replacetrack in Chrome

### ISSUE THREAD

**Issue by buzeandrei** [OpenVidu/openvidu#449]
Replace track functionality on latest version openvidu-browser (2.13.0) seems to unmute the video element on Chrome, but not on FireFox. Any idea why this happens and if we can prevent it?

**Comment by pabloFuente** [comment]
Can you describe in more detail the issue you are having? The issue template is there for this reason ;). In fact, this problem seems pretty much perfect for the issue template. With the information asked in the template, we will be able to replicate it and if there's a bug, to fix it.

Regards.

**Comment by buzeandrei** [comment]
**Describe the bug**
When using Publisher.replaceTrack the audio track is being unmuted in Chrome and audio starts playing.

**Expected behavior**
Audio element should remain muted in case of replace track.

**Wrong current behavior**
Audio feedback is started and you cannot mute the element created for the publisher.

**OpenVidu how to replicate the error**
`
let constraints = {
                  audio: {deviceId: trackId ? {exact: trackId} : undefined}
};
                navigator.mediaDevices.getUserMedia(constraints).then(function (stream) {
                  vm.publisher.replaceTrack(stream.getAudioTracks()[0]).then(() => {
                       // cannot mute back the audio source
                  });
                });
`

**OpenVidu deployment info**
docker run \
    -p 4443:4443 \
    --rm \
    --network="host" \
    -e OPENVIDU_SECRET=MY_SECRET \
    -e OPENVIDU_CDR=true \
    -e OPENVIDU_WEBHOOK=true \
    -e OPENVIDU_WEBHOOK_ENDPOINT=https://localhost:9000/webhook \
    -e OPENVIDU_WEBHOOK_HEADERS=[\"Authorization:\ Basic\ MY_SECRET\"] \
    openvidu/openvidu-server-kms:2.13.0

**Client device info (if applicable)**
- Chrome 81.0.4044.122 (Official Build) (64-bit) on macOS Catalina 10.15

**Additional context**
As in examples, we are using
`vm.publisher.on('videoElementCreated', (event) => {
                $(event.element).prop('muted', true); // To mute local video
              });`

**Comment by pabloFuente** [comment]
Thank you, we will take a look

**Comment by AlexStreaming** [comment]
I have the same problem, with the replaceTrack function for audio in openvidu version 2.13
When I make an audio device change, I start listening to my own audio.

**Comment by micaelgallego** [comment]
Please @AlexStreaming, it seems a different problem. Can you please create another issue?

**Comment by SSnake77** [comment]
I'm using openvidu-browser 2.11 and I had the same issues.
The problems seem to be related to the getMediaStream() method inside Publisher's publishAudio() method, that returns the old (replaced) mediaStream object:
https://github.com/OpenVidu/openvidu/blob/v2.11.0/openvidu-browser/src/OpenVidu/Publisher.ts#L110

To enable the mute/unmute feature on the new audio track, I've added the following line just after the replaceTrack call:

`publisher.stream.setMediaStream(mediaStream);`

where mediaStream is the stream used to get the audio track for the replaceTrack call.

To maintain the mute status when switching microphone, I've added the following code just after the setMediaStream call:
```
if (!publisher.stream.audioActive) {
  publisher.publishAudio(true);
  publisher.publishAudio(false);
}
```
This just checks if the audio was active before the microphone switching, and disable it again (I've also had to enable it before, otherwise this was not working).

Hope it helps.

**Comment by buzeandrei** [comment]
I think this disables the audio track from being sent all together. We experience mic unmuting on the publisher side (it's starts echoing). Any other updates?

**Comment by cuca24** [comment]
This seems to be an issue in Publisher class inside replaceMediaStreamTrack function. 

https://github.com/OpenVidu/openvidu/blob/43bf7f44c23bc326b9401807bb8b9999bde498d0/openvidu-browser/src/OpenVidu/Publisher.ts#L310

When called you can hear your own sound as playback.

**Comment by videojedi** [comment]
I think maybe, I am hearing a related audio issue when using the replacetrack function. Even though my all my HTML video windows are muted, I still hear the audio feed. If I unmute the video player, then you hear the same audio again but with a tiny delay on it. Have tried removing all audio tracks just before replacing with new track, but result is the same, two slightly delayed copies of the same source.

**Comment by alecpl** [comment]
I also have the same issue in Chrome. I found a workaround. Call `publisher.videoReference.muted = true` after replaceTrack().

What the heck is this (detached) video element reference used for?

**Comment by videojedi** [comment]
thanks! That workaround fixes the issue for me.
Before, even if I removed every element in Chrome debug, back to <HTML></HTML> I could still hear the audio stream...? :)

RB

**Comment by pabloFuente** [comment]
Hi,

A couple of recent commits should fix this issue. On the one hand, we now honor the previous muted/unmuted state of the replaced track, setting the new track to that same state. And also by default the `videoReference` element that @alecpl was talking about here https://github.com/OpenVidu/openvidu/issues/449#issuecomment-774014610 is also muted by default (this reference is needed to gather and monitoring specific properties of the media streams, that are only available when actually attached to an HTMLVideoElement).

Closing this issue, as in master branch this should be fixed by now.
