### ISSUE TITLE
Deployment documentation for Ubuntu was removed

### ISSUE THREAD

**Issue by martin-petzold** [OpenVidu/openvidu#460]
In 2.12.0 there was a deployment documentation for Ubuntu. This is missing in 2.13.0. I don't think it makes sense to force people to use Docker. There is actually no real benefit in using Docker.

**Comment by pabloFuente** [comment]
Not a bug or an issue. Use [the forum](https://openvidu.discourse.group/) for this kind of questions.
`There is actually no real benefit in using Docker.` I beg to differ. It makes a **HUGE** difference in terms of adminitration and operation tasks. It allows installing OpenVidu not only in a specific version of Ubuntu, but on any Linux modern distribution. It homogenizes all OpenVidu deployments out there, so every OpenVidu deployment can benefit of the same fixes and changes. Upgrading/Downgrading a dockerized OpenVidu deployment is a matter of chaning a tag in a file, instead of uninstalling and re-installing native software. Now AWS deployments can boot up in 2 minutes instead of 15 minutes.

In fact, I cannot really think of any other recent change in OpenVidu that brings more benefits than a Docker deployment.
