### ISSUE TITLE
Composed record without audio after publisher has network problems.

### ISSUE THREAD

**Issue by TBorgert** [OpenVidu/openvidu#485]
**Describe the bug**
Composed recording lost audio after publisher experienced network problems.

**Expected behavior**
Composed recording with audio in entire file.

**Wrong current behavior**

A very common problem that we have in a production environment, are problems with the audio in the composed recording. When a publisher has a connection problem and needs to return to the room, the audio of the recording is muted for the remainder of the recording. I tried to simulate this in a development environment  several times without success, but today, creating a room in the production environment, the problem happened to me.
I used clumsy software to simulate a connection with high latency and packet loss, which results in the loss of connection. After returning to the room the audio of the recording is gone.

The CPU for this server (c5.24xlarge) was around 40% (13 simultaneous composed records at the time of testing ).

I believe that maybe have something to do with race conditions, as I am able to reproduce this in production only, in development environment  I cannot reproduce this scenario yet.

I'm pasting the logs below and also a mp4 of composed record. The connection was lost near 5:24 minutes of the video, when returning at 6:40 there is no more audio in the recording.

***
[openvidulogs-Sala24332.log](https://github.com/OpenVidu/openvidu/files/4697188/openvidulogs-Sala24332.log)

https://drive.google.com/file/d/1enyUajyGWxShfWBUWEN8gUqWrL785j4P/view?usp=sharing

I am filtering the logs by the name of the room, using the following command:

  ./openvidu logs | grep Sala24332

I would like to know if this is the best way to filter the logs, so that you can analyze it. 

**OpenVidu deployment info**
 Ubuntu 18.04.4 LTS in AWS using On Premises Openvidu 2.14 tutorial. Im using   openvidu/openvidu-server:2.14.1-beta4 image.

**Comment by pjuhasz** [comment]
Could you try with INDIVIDUAL recordings?

In our setup we record in INDIVIDUAL mode and create composite recordings later in a postprocessing step, and during a recent testing run we've noticed that for some sessions the sound stopped being recorded at one point for one of the participants. He seemed to have a bad network connection, and in the affected recordings the call was fine up to a point, then there was a disruption, and from then on there was no sound on his channel (except some click-like noises), and A/V sync was lost too. From the reactions of the other party (which were recorded) it appears that they heard each other during the session, the audio is missing from the recorded stream only.

It's not necessarily the same problem, but it sounded similar enough to warrant the observation.

**Comment by TBorgert** [comment]
I tried using INDIVIDUAL recording but I was unable to reproduce the problem in my development environment. I also had difficulties to reproduce this with COMPOSED, I only succeeded when we were having simultaneous conferences in our production environment.
To change that in production I would need to be able to do like you, joining the files in post-processing. Would you mind providing us with details on how this post processing is done?
Anyway, I'm trying to simulate several conferences to see if the problem is also repeated.

**Comment by pjuhasz** [comment]
It turns out I was mistaken, the apparent problem was a result of the post-processing, so it's not relevant to this issue.

This post-processing is an ffmpeg command, triggered by a RecordingStatusChanged event, that takes the two .webm files and overlays one on top of the other, mixing the two audio channels. It turns out you have to use -acodec libopus, because ffmpeg's native decoder can't handle the files that typically result when the network connection is bad.

**Comment by micaelgallego** [comment]
Glad to hear your problem is now solved.

**Comment by BritoMatheus** [comment]
> It turns out I was mistaken, the apparent problem was a result of the post-processing, so it's not relevant to this issue.
> 
> This post-processing is an ffmpeg command, triggered by a RecordingStatusChanged event, that takes the two .webm files and overlays one on top of the other, mixing the two audio channels. It turns out you have to use -acodec libopus, because ffmpeg's native decoder can't handle the files that typically result when the network connection is bad.

I'm trying to do it but no success. Can you send commands that you are using?

Thanks!!

**Comment by TBorgert** [comment]
> Glad to hear your problem is now solved.

Sorry Micael, a possibly related problem of other user are solved but the original problem related by me still occurs. Would is possibly reopen this bug?

**Comment by beyondlevi** [comment]
> > Glad to hear your problem is now solved.
> 
> Sorry @micaelgallego , a possibly related problem of other user are solved but the original problem related by me still occurs. Would is possibly reopen this bug?

I think it must be related to the reconnection issues that have been discussed in the past few days:
For some reasons (difficult to reproduce) when a user has a bad connection and loses it for a few milliseconds, OpenVidu tries to reconnect all streams, but sometimes one or two streams are still frozen for some users (not all) . If the user stops publishing (our application allows this) and republishes without updating the page, the frozen stream is destroyed and the new stream is 100% functional. To be clear: a user with such a bad connection, after his silent reconnection by openvidu-browser may have all streams working normally, but his stream may be frozen for users who have a stable connection, because openvidu-browser is not able to detect the freeze and subscribe to the stream again.

Bringing this to your case, in which you are making the composed recording, a user with a bad connection can affect the recording (ghost) user by being reconnected and the stream becomes frozen.

In my frustrated attempts to reproduce this error in a development environment, I really noticed that it occurs more frequently when we have many users connected in the session (not necessarily many PUBLISHERS).

But what is clear to me is that these problems could be solved in openvidu-browser. For now, I keep looking for alternatives to check frozen streams in my application, to destroy and re-subscribe them.

**Comment by pjuhasz** [comment]
> I'm trying to do it but no success. Can you send commands that you are using?
> 
> Thanks!!

FWIW, see the attached perl script that contains the ffmpeg command line.

[openvidu-recording-compositor.pl.txt](https://github.com/OpenVidu/openvidu/files/4718998/openvidu-recording-compositor.pl.txt)

**Comment by micaelgallego** [comment]
Thank you @pjuhasz

**Comment by micaelgallego** [comment]
If have problems when some users are reconnected due to network connections, maybe this property can be helpful:

https://docs.openvidu.io/en/2.14.0/api/openvidu-browser/interfaces/openviduadvancedconfiguration.html#forcemediareconnectionafternetworkdrop

**Comment by TBorgert** [comment]
This problem was solved on 2.14 / 2.15 version (I don't remember exactly) and it never happened again. You can close this issue. Thanks @pjuhasz @micaelgallego @beyondlevi
