### ISSUE TITLE
Samsung Internet Browsers in Samsung devices

### ISSUE THREAD

**Issue by CSantosM** [OpenVidu/openvidu#489]
Samsung Internet Browser is not supported in Samsung devices because of the platform name in Samsung devices is quite different than others (tested in Xiaomi device). 

See: https://openvidu.discourse.group/t/samsung-web-browser-11-2-is-not-supported/1037/5

**Comment by conradoac** [comment]
Hi @CSantosM, thanks for creating an issue about it.

Would you mind changing the documentation? I am not sure that it is ok to say that OpenVidu supports Samsung Internet. Especially if it is not supported in Samsung devices.

I had many problems changing our production environment to update from 2.12.0 to 2.14.0. We did it just because of this specific change.

I think it is interesting to share our case and explain why we need to support this browser. I know that Samsung Internet is not a largely used browser. However, our users receive a link to access their call on e-mail, and almost every Samsung device has Samsung Internet as its default browser. When they click on the link we need to say that they need to change to another browser, and It feels like a really bad user experience.

**Comment by CSantosM** [comment]
Hello @conradoac ,

Sorry for the inconvenience, We tested the support of  Samsung Internet Browser in a Xiaomi device and it was working fine. We don't have Samsung device and We couldn't test with this hardware but thanks to the community we can know that the user agent of Samsung devices was quite different to the Xiamomi devices for Samsung Internet Browser. 

We commited the bug fix and this is added in master branch. This week whe'll release a new version and this change will be official. However, if it's urgent for you, you can use the master code of openvidu-browser to support this feature. 


I hope you understand and sorry again.

**Comment by conradoac** [comment]
@CSantosM Thanks for explaining what happened.
If the new version release is this week I think it is worth it waiting for it.

There is no need to apologize. OpenVidu has been very helpful, especially after the COVID-19 pandemic.
