### ISSUE TITLE
unable to change proxy of openvidu version 2.15.0

### ISSUE THREAD

**Issue by designerprasan007** [OpenVidu/openvidu#517]
hi we are working on openvidu streaming and it's working a charm, but now we want to setup openvidu in our production mode so we need to remove the port assigned to it and we want to make it work only with the Domain name, we took code from this github link https://github.com/OpenVidu/openvidu-tutorials and from this we are using https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-js-node (openvidu-js-node). and this is our current working link https://vc.enlyvo.com:5000/?uname=enteryourname&sname=mysesion as you see here we have assigned 5000 port to run it, but we need to remove that and make url as https://vc.enlyvo.com/?uname=enteryourname&sname=mysesion , hope you understood what I meant, thank you for waiting for a response.

**Comment by pabloFuente** [comment]
Hi,

To get support use the public forum: https://openvidu.discourse.group/

OpenVidu issue tracker is only meant for possible bugs in the platform, as you will know for the template you had to overwrite in order to open it. Describe in detail what you want to achieve in a new forum entry.

Regards.
