### ISSUE TITLE
Support changing default coturn port

### ISSUE THREAD

**Issue by steelden** [OpenVidu/openvidu#518]
**Describe the bug**
As of now (2.15.0) there is no way to change coturn's default port.
(Well there IS but its quite painful)

**Expected behavior**
There is an environment configuration setting TURN_PUBLIC_PORT that specifies public and internal port number for coturn (similar to TURN_PUBLIC_IP).
And its being forwarded to clients (like openvidu-browser) inside token query parameter coturnPort=nnnn (similar to coturnIp).

**Wrong current behavior**
The default coturn port value is hardcoded in coturn's docker configuration, openvidu-server and openvidu-browser.

**OpenVidu tutorial where to replicate the error**
You can try to change the default port from 3478 to something else. There is no clear way without rebuilding containers and other clever hacks.

**OpenVidu deployment info**
N/A

**Client device info (if applicable)**
N/A

**Screenshots**
N/A

**Additional context**
I stumbled into this problem while trying to upgrade from 2.11.0.
We had our coturn for openvidu listen on port 3479 as 3478 is already used for another coturn server.
I like the new dockerized setup so much but I'm kinda stuck now being unable to use any port other than 3478.

**Comment by pabloFuente** [comment]
Hi,

You are right: changing this specific port is complicated, because multiple modules and levels are involved and must be aware of it. This is a long discussed topic: should we invest time and resources to allow changing all the default ports of each of the different services that make up an OpenVidu production deployment? We decided to go for a middle-ground solution, at least for now: you are able to easily change with a single porperty the exposed public port (HTTPS and HTTP) of your OpenVidu deployment, which is the most important, but other ports... not for now. Specifically the COTURN port would require multiple modifications in different containers, and also in the client side. Documentation also assumes the COTURN  port is 3478, and allowing to change it means opening another source of trouble when deploying OpenVidu. We've seen this in the past when "loosening" deployment instructions and restrictions.

As it is right now, I'm pretty sure it will be easier for you to change the default port in your other service. Having 2 different ngnix services in the same machine were OpenVidu is deployed is also not ideal, of course. This kind of problems are always going to show up when installing conflicted services in the same server. An easy solution for your problem would be hosting your other ngnix service in a different machine, of course. But that's up to you.

Regards.

**Comment by steelden** [comment]
Hi,

Yeah, I'd really like to change the other's coturn port. But you see, the problem is its another OpenVidu installation.
Thats my company's 2nd production video server. And yes, they both use the same NATed external ip.

Until now it was not much of a problem to configure 2 OpenVidu servers on 1 ip.
The only thing that prevents such configuration now is ability to move coturn to another port.

And you can't really use one coturn server for both installations because of OpenVidu clearing all of the redis db on startup.

So thats kind of a deadlock here.

**Comment by basicmonkey** [comment]
We're having lots of issues with restrictive company firewalls and it'd be great if we could put TURN on port 80 or similar to help users connect. (I only use port 443 on the server for API calls).

**Comment by micaelgallego** [comment]
If you want to deploy TURN server in 80 or 443 port, then you will need to deploy it in their own server or configure two IPs in the same server. 

We will think about your feature request

**Comment by eduardobaitello** [comment]
I just set the `TURN_LISTEN_PORT` `32478` to env var, and I got this:

> TURN public IP: xxx.xxx.xx.xxx
> TURN listening port: 32478
> REDIS IP: redis-service
> Defined min port coturn: 57001
> Defined max port coturn: 65535
> Waiting turnserver to be running
> ....

**Comment by basicmonkey** [comment]
Thank you. Could I create a port alias of the main TURN server port and change it in the OpenVidu browser client? Could I add it to the FreeICE list?
