### ISSUE TITLE
Delay when streaming IP Camera

### ISSUE THREAD

**Issue by dhavalsolankislk** [OpenVidu/openvidu#530]
Hello, 
We are using open vidu in our application. We are streaming ip camreas in our project. But we are getting delay of 3-4 seconds compared to actual streaming. Is there any way we can decrease delay of the streaming.

**Comment by dhavalsolankislk** [comment]
any update ?

**Comment by pabloFuente** [comment]
The delay may be caused by the default value that the receiving buffer has in OpenVidu Server for IP cameras.
We have added a new **[IP camera configuration parameter](https://docs.openvidu.io/en/2.15.0/advanced-features/ip-cameras/#configuring-ip-cameras)** in PR **https://github.com/OpenVidu/openvidu/pull/540** that will allow changing the default 2000 millisecond buffer to the value the developer wants. This property should be treated carefully, because RTSP cameras don't have buffer controls to deal with network quality problems. If the camera is in the same network or in a very stable one than OpenVidu Server deployment, then this buffer can be greatly reduced. But if the network between the camera and OpenVidu Server might be unstable, then problems in the streaming may appear.

You can test this new paramenter "networkCache" in beta release of OpenVidu Server: [openvidu/openvidu-server:2.16.0-beta1](https://hub.docker.com/layers/openvidu/openvidu-server/2.16.0-beta1/images/sha256-4f1a9c2a5a39ca27e91849c70ef74ee233f3e8ab197a406e61318f71c32852cb?context=explore). Will be officially available and properly documented in release 2.16.0.
