### ISSUE TITLE
how to protect openvideo-sever rpchander websocket connection security

### ISSUE THREAD

**Issue by RobinsChens** [OpenVidu/openvidu#633]
the rpchander websocket connection doesn't have intercepter or security handler,can you add some security resolutions for it ,just like netty-socketio project

**Comment by cruizba** [comment]
To make use of all the operations, openvidu-browser calls `joinRoom` rpc method which should have in its parameter a token generated previously: https://docs.openvidu.io/en/2.18.0/developing/rpc/#joinroom. Without this token, any of the methods defined can not be invoked. So operations are protected with OpenVidu tokens.

In other words, Security is implemented because to stablish a websocket connection it is necessary that the first operation have a valid token generated previously.
