### ISSUE TITLE
don't able to receive the video data in the android

### ISSUE THREAD

**Issue by rohit050713** [OpenVidu/openvidu#644]
i have downloaded the code from the openvidu github repo for android but it is not working properly. I am not able to see the video of the people who have joined the video call i am just able to see the name of the person who have joined the call but video is black.See the screenshot attached to this.
![Screenshot (53)](https://user-images.githubusercontent.com/66115729/126462959-119e002b-7703-4bc8-8f95-d2df0c895d07.png)

**Comment by cruizba** [comment]
Did you followed official instructions?: https://docs.openvidu.io/en/2.18.0/tutorials/openvidu-android/

Also don't spam everywhere, I see you posting in openvidu forum. I'll close this issue and continue in the forum because this is not an OpenVidu bug...

https://openvidu.discourse.group/t/openvidu-android-sample-code-not-working/3235
