### ISSUE TITLE
/openvidu/api/recordings/start

### ISSUE THREAD

**Issue by bobby-8084** [OpenVidu/openvidu#782]
1.Recordings Api not working
https://xxxxx.com/openvidu/recordings/start
body { "session": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "outputMode": "INDIVIDUAL" }
show this error of response
{
    "timestamp": "2023-01-20T07:20:26.177+00:00",
    "status": 401,
    "error": "Unauthorized",
    "message": "",
    "path": "/openvidu/api/recordings/start"
}
Can anyone help on this

**Comment by CSantosM** [comment]
If you had read the documentation you would not think this is a bug.
The REST API documentation is clear enough https://docs.openvidu.io/en/2.25.0/reference-docs/REST-API/#post-recording-start. 

Your reqquest is wrong. As the response says, You are not authorized because you are missing the credentials.

**Comment by bobby-8084** [comment]
I added Authorization Headers as Basic Auth

username:xxxxx
password:xxxxxx
