### ISSUE TITLE
Confirmation alert about certificate error is appearing after losing connection (not certificate error)

### ISSUE THREAD

**Issue by romandragan** [OpenVidu/openvidu#79]
https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/Session.ts#L739:

```ts
if (!this.connection) {

            console.warn('Not connected to session: if you are not debugging, this is probably a certificate error');

            const url = 'https://' + this.openvidu.getWsUri().split('wss://')[1].split('/openvidu')[0];
            if (window.confirm('If you are not debugging, this is probably a certificate error at \"' + url + '\"\n\nClick OK to navigate and accept it')) {
                location.assign(url + '/accept-certificate');
            }
            return;
        }
```

`!this.connection` is probably not always working properly. It returns `true` event if client can't connect to server due to timeout or if server is refusing connections by any other reason, not just certificate error.

Also, I suppose, it's not best option to directly show `window.confirm` to user.

We're using `openvidu-browser` in HTTPS production with valid certificate, but users very often see this confirmation window.

Maybe you can improve this code, so developers can use callback or Promise's catch, to catch this issue.

**Comment by pabloFuente** [comment]
Yes, we can give this idea a go. The main reason this alert is shown by default is something that goes back a long way, from the beginnings of OpenVidu. When trying any tutorial or sample application, it is inevitable that the firt time connecting to OpenVidu Server the communication fails because of the self-signed certificate issue, until the user accepts it. And unfortunately it is impossible to differentiate with browser's API if the cause of the error is due to a certificate issue, a network error or any other kind of problem. So the lowest level code segment where to listen to a certificate problem was in fact this `onLostConnection` event.

But the good news are that with the 2.0.0 refactorization, every tutorial and sample application now makes use of the API REST to get a valid token from OpenVidu Server before initializing and connecting to a session in the client-side (before this, those applications with no backend were building a token on their own, so the first communication with OpenVidu Server was in fact  method `Session.connect(...)` (there was no other place where to attend the slef-sigend certificate problem)

Now we could listen to this API REST call in every application and warn the user about the certificate issue in that context. To sum up: listen to this error from an application point of view, not from OpenVidu Browser library point of view (and therefore liberating our websocket `onLostConnection` event).

**Comment by romandragan** [comment]
@pabloFuente 

Okay, great. But what can I do to ignore `onLostConnection`? I receive it and therefore `window.confirm` very often. Can I submit PR with removing `window.confirm` logic?

**Comment by pabloFuente** [comment]
We have fix this in release 2.2.0, launching in the following hours.

**Comment by pabloFuente** [comment]
You can still know when the websocket connection has been lost by listening to [SessionDisconnectedEvent](https://openvidu.io/api/openvidu-browser/classes/sessiondisconnectedevent.html) (reason property will be 'networkDisconnect' in this case)

**Comment by romandragan** [comment]
@pabloFuente 

By the way, why OpenVidu WS connection always tries to reconnect after `networkDisconnect`? Can I stop this behaviour is some way?
