### ISSUE TITLE
Certificat error

### ISSUE THREAD

**Issue by lotfiGipsyKing** [OpenVidu/openvidu#96]
i am trying to setup a openvidu server, i followed the steps in the Docs to deploy using Docker in my remote linux server, but when i run the client side angular application i get this popup : 

![image](https://user-images.githubusercontent.com/12205090/42766826-5b7038e8-8913-11e8-9d7f-99b1967471be.png)
can someone help ?

**Comment by pabloFuente** [comment]
Have you followed this instructions?: https://openvidu.io/docs/deployment/deploying-ubuntu/

**Comment by lotfiGipsyKing** [comment]
yes, i followed the instructions in the link and also the instruction using docker, and both given me the same issue, knowing that i run the client side(angular) in my local machine and the server side (openvidu-server) in a remote ubuntu server.

**Comment by pabloFuente** [comment]
And when you navigate to the exact URL shown in the alert (the one you hid), what can you see?

**Comment by lotfiGipsyKing** [comment]
i see a page to test the server, wheb i click on the test event, it shown me this:

Connected to session

Video element created

Camera access allowed

Stream created

**Comment by pabloFuente** [comment]
Okey, some things I can tell you right now:

1) If you have followed this instructions (https://openvidu.io/docs/deployment/deploying-ubuntu/), then you can see that the Dockerized version of OpenVidu Server is not supported right now. It clearly says to use the JAR version of OpenVidu Server in the [8th point](https://openvidu.io/docs/deployment/deploying-ubuntu/#8-init-openvidu-server-jar-executable). It will work with the Docker container, of course, but not on every scenario. This is because there's no compatibilty between TURN server and Docker container of OpenVidu Server yet. And if your test stopped on "Stream created" message, this means that you have no media connection to your OpenVidu Server. It should finish with "Stream playing" and your remote video being shown.

2) If you are able to connect to OpenVidu Server Dashboard through `https://YOUR_IP:4443` but that alert warning about `https://YOUR_IP:4443` is being shown in your app when calling `Session.connect()`, then the only possiblity is that the certificate served by your OpenVidu Server is not valid and that you have not accepted it yet. That's what the alert is in fact stating.

I'm afraid I can't be of any more help. You can post here the log shown by the browser's console when you try to connect to a Session, to see if there is any more useful information.

Regards.

**Comment by oliverwh** [comment]
Bumped into same issue. Console log:

'OpenVidu' initialized
XHR finished loading: OPTIONS "https://x:4443/api/sessions"
POST https://x:4443/api/sessions 401 ()
No connection to OpenVidu Server. This may be a certificate error at https://x:4443
XHR failed loading: POST "https://x:4443/api/sessions".
Leaving Session (forced=false)
You were not connected to the session undefined

Testing server works just fine.

**Comment by sourabh947** [comment]
> i am trying to setup a openvidu server, i followed the steps in the Docs to deploy using Docker in my remote linux server, but when i run the client side angular application i get this popup :
> 
> ![image](https://user-images.githubusercontent.com/12205090/42766826-5b7038e8-8913-11e8-9d7f-99b1967471be.png)
> can someone help 
i am also getting same error 
can someone help ?

**Comment by lotfiGipsyKing** [comment]
@sourabh947  just go to the link that you hidden , and accept the certificat, in chrome : 

![image](https://user-images.githubusercontent.com/12205090/51756116-952bdc00-20c0-11e9-9392-a521cb71a1fe.png)

**Comment by kpremsai** [comment]
Hi,
I am new to OpenVidu and I am trying to run OpenVidu demo on my server.
when I was trying to creating meeting I am getting this error
I am getting below error and I am not going to further step
please help me how to solve below error

webSocketWithReconnection.js:161 WebSocket connection to 'wss://localhost:4443/openvidu' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Below I attached a snapshot of I am getting the error.

![Screenshot_2](https://user-images.githubusercontent.com/45309411/62195058-c69ba200-b398-11e9-9ec5-df929aa1ba4c.png)

Thanks.

**Comment by micaelgallego** [comment]
OpenVidu server is not properly configured because public.url points to its default location: localhost:4443. You have to define public URL in the server when deployed. Please follow instructions on the web page.

**Comment by abdullahgulyani** [comment]
![Capture](https://user-images.githubusercontent.com/67911849/86767503-82635800-c065-11ea-9541-54bf7e4bf500.PNG)
 can anyone solve this issue

**Comment by micaelgallego** [comment]
Please describe how you have deployed OpenVidu in the public forum https://openvidu.discourse.group.

**Comment by abdullahgulyani** [comment]
![1](https://user-images.githubusercontent.com/67911849/87518078-3cc41200-c699-11ea-8109-2f313afe3fff.PNG)
![2](https://user-images.githubusercontent.com/67911849/87518084-3e8dd580-c699-11ea-820d-622baee64f16.PNG)
![3](https://user-images.githubusercontent.com/67911849/87518088-3f266c00-c699-11ea-89a5-07a1e906b48b.PNG)
im getting in a error when connect to open vidu server
Anyone help?

**Comment by micaelgallego** [comment]
Use the public forum for problems with deployment
