### ISSUE TITLE
Can I subscribe/unsubscribe to audio or video dynamically?

### ISSUE THREAD

**Issue by willylee007** [OpenVidu/openvidu#97]
Thanks for the OpenViudu-Browser SDK.

I've found the documentation [here](https://openvidu.io/api/openvidu-browser/interfaces/subscriberproperties.html#subscribetoaudio), and it shows it can subscribe to audio or video. 

But it just remove video track or audio track from MediaStream not remote participants after I read the source code.

So If there is a way to subscribe/unsubscribe audio track or video track from remote participant dynamically?And did it needs KMS's supports?

Best regards!

**Comment by pabloFuente** [comment]
Hi,

`subscribToAudio` and `subscribeToVideo` actually just enable/disable the audio and video track in a WebRTC-browser-level. This has been implemented like this because the other alternative would have been doing exactly the same thing but in the KMS side: mute or unmute certain track from a WebRtcEndpoint representing a subscriber.

The act of "really" completely removing the audio or video track would mean a dynamic renegotiation process of the WebRtc connections, which Kurento doesn't support. And on the other hand muting the audio and/or video tracks in the client side is in fact a pretty good solution, as it is fast, has minimal impact and the network cost of a disabled audio or video track is really low.

Hope you finde this info useful. Regards

**Comment by willylee007** [comment]
Hi~

In some scenarios, it may be necessary to unsubscribe from video or audio dynamically, for example: when a user is using a mobile network and the network is in bad condition(I'm developing an conference App(mobile) base on OpenVidu-Server and KMS currently), the user will only receive audio when they join a meeting and then receive video separately to a user, and so on.

It seems like amount of work for Kurento to do this. Stay tuned~

Best regards~!

**Comment by lucassaid** [comment]
Hi, I don't know if I should write this here, but I read this

> the network cost of a disabled audio or video track is really low.

well, Im working with subscribeToVideo(false) and it seems to work since the video element goes black, but the network cost doesn't change... I think Im measuring it right because when the publisher stop publishing it's video, I can see how the network cost decreases

**Comment by CSantosM** [comment]
We just tested if the network cost decreases muting audio and video in a session of two users. 

Muting audio and video in both users, we can see a high network usage decrease. 
![Video and audio muted ](https://user-images.githubusercontent.com/10628395/82193792-306c4480-98f6-11ea-9d45-333cdbb8e7e8.png)

However, we will work on this way to optimize OpenVidu performance.
If you notice something weird on this way, please open another issue.

Regards

**Comment by lucassaid** [comment]
Thaks for reply, and yes, muting video from the publisher decreases the network cost. But when using ubscribeToVideo(false) from a subscriber, I can not see any decrease...
I'm working in a project where I have multiple 'pages' of streams (like Zoom), and the goal is to receive all the audios, but disable (and stop downloading) the videos that aren't in the current page.

**Comment by micaelgallego** [comment]
Thank you for the suggestion @lucassaid.

We will consider it in our roadmap.

**Comment by rfazi** [comment]
Any news about this?

**Comment by chinarui-na** [comment]
Any news about this?

**Comment by chinarui-na** [comment]
> Thaks for reply, and yes, muting video from the publisher decreases the network cost. But when using subscribeToVideo(false) from a subscriber, I can not see any decrease... I'm working in a project where I have multiple 'pages' of streams (like Zoom), and the goal is to receive all the audios, but disable (and stop downloading) the videos that aren't in the current page.

Did you solve it？
